Model.com enviroment
Google Account kkshah0811@gmail.com

In [1]:
import os
import torch
import shutil
import psutil

# Get CPU count
print(f"CPU cores: {os.cpu_count()}")

# Get total system RAM
total_ram = psutil.virtual_memory().total / (1024**3) # Convert bytes to GB
print(f"System RAM: {total_ram:.2f} GB")

# Get GPU name and VRAM
if torch.cuda.is_available():
    gpu_name = torch.cuda.get_device_name(0)
    gpu_vram = torch.cuda.get_device_properties(0).total_memory / (1024**3) # Convert bytes to GB
    print(f"GPU: {gpu_name}")
    print(f"GPU VRAM: {gpu_vram:.2f} GB")
else:
    print("No GPU available.")

# Get disk usage
total, used, free = shutil.disk_usage("/")
print(f"Disk Space: Total={total / (1024**3):.2f} GB, Used={used / (1024**3):.2f} GB, Free={free / (1024**3):.2f} GB")

CPU cores: 43
System RAM: 1006.83 GB
GPU: NVIDIA A100 80GB PCIe
GPU VRAM: 79.25 GB
Disk Space: Total=512.00 GB, Used=0.07 GB, Free=511.93 GB

In [2]:
!pip install unsloth

Collecting unsloth
  Downloading unsloth-2025.9.6-py3-none-any.whl.metadata (54 kB)
Collecting unsloth_zoo>=2025.9.7 (from unsloth)
  Downloading unsloth_zoo-2025.9.8-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/site-packages (from unsloth) (2.8.0+cu129)
Collecting xformers>=0.0.27.post2 (from unsloth)
  Downloading xformers-0.0.32.post2-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (1.1 kB)
Collecting bitsandbytes (from unsloth)
  Downloading bitsandbytes-0.47.0-py3-none-manylinux_2_24_x86_64.whl.metadata (11 kB)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/site-packages (from unsloth) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/site-packages (from unsloth) (25.0)
Collecting tyro (from unsloth)
  Downloading tyro-0.9.32-py3-none-any.whl.metadata (11 kB)
Collecting transformers!=4.47.0,!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.55.4,>=4.51.3 (from unsloth)
  Downloading transformers-4.55.4-py3-none-any.whl.metadata (41 kB)
Collecting datasets<4.0.0,>=3.4.1 (from unsloth)
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/site-packages (from unsloth) (0.2.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/site-packages (from unsloth) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/site-packages (from unsloth) (7.0.0)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/site-packages (from unsloth) (0.45.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/site-packages (from unsloth) (2.1.2)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/site-packages (from unsloth) (1.10.1)
Collecting trl!=0.15.0,!=0.19.0,!=0.9.0,!=0.9.1,!=0.9.2,!=0.9.3,>=0.7.9 (from unsloth)
  Downloading trl-0.23.0-py3-none-any.whl.metadata (11 kB)
Collecting peft!=0.11.0,>=0.7.1 (from unsloth)
  Downloading peft-0.17.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/site-packages (from unsloth) (5.29.2)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/site-packages (from unsloth) (0.34.4)
Collecting hf_transfer (from unsloth)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/site-packages (from unsloth) (0.35.1)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/site-packages (from unsloth) (0.23.0+cu129)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/site-packages (from accelerate>=0.34.1->unsloth) (6.0.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/site-packages (from accelerate>=0.34.1->unsloth) (0.6.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/site-packages (from datasets<4.0.0,>=3.4.1->unsloth) (3.13.1)
Collecting pyarrow>=15.0.0 (from datasets<4.0.0,>=3.4.1->unsloth)
  Downloading pyarrow-21.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting dill<0.3.9,>=0.3.0 (from datasets<4.0.0,>=3.4.1->unsloth)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/site-packages (from datasets<4.0.0,>=3.4.1->unsloth) (2.3.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/site-packages (from datasets<4.0.0,>=3.4.1->unsloth) (2.32.5)
Collecting xxhash (from datasets<4.0.0,>=3.4.1->unsloth)
  Downloading xxhash-3.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets<4.0.0,>=3.4.1->unsloth)
  Downloading multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/site-packages (from huggingface_hub>=0.34.0->unsloth) (4.12.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/site-packages (from huggingface_hub>=0.34.0->unsloth) (1.1.9)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (70.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.9.86 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (12.9.86)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.9.79 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (12.9.79)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.9.79 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (12.9.79)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.9.1.4 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (12.9.1.4)
Requirement already satisfied: nvidia-cufft-cu12==11.4.1.4 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (11.4.1.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.10.19 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (10.3.10.19)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.5.82 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (11.7.5.82)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.10.65 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (12.5.10.65)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.9.79 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (12.9.79)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.9.86 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (12.9.86)
Requirement already satisfied: nvidia-cufile-cu12==1.14.1.1 in /usr/local/lib/python3.12/site-packages (from torch>=2.4.0->unsloth) (1.14.1.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/site-packages (from transformers!=4.47.0,!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.55.4,>=4.51.3->unsloth) (2025.9.1)
Collecting tokenizers<0.22,>=0.21 (from transformers!=4.47.0,!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.55.4,>=4.51.3->unsloth)
  Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
INFO: pip is looking at multiple versions of trl to determine which version is compatible with other requirements. This could take a while.
Collecting trl!=0.15.0,!=0.19.0,!=0.9.0,!=0.9.1,!=0.9.2,!=0.9.3,>=0.7.9 (from unsloth)
  Downloading trl-0.22.2-py3-none-any.whl.metadata (11 kB)
Collecting torchao (from unsloth_zoo>=2025.9.7->unsloth)
  Downloading torchao-0.13.0-1-cp39-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (19 kB)
Collecting cut_cross_entropy (from unsloth_zoo>=2025.9.7->unsloth)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/site-packages (from unsloth_zoo>=2025.9.7->unsloth) (11.0.0)
Collecting msgspec (from unsloth_zoo>=2025.9.7->unsloth)
  Downloading msgspec-0.19.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.9 kB)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/site-packages (from diffusers->unsloth) (8.7.0)
Collecting docstring-parser>=0.15 (from tyro->unsloth)
  Downloading docstring_parser-0.17.0-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=11.1.0 in /usr/local/lib/python3.12/site-packages (from tyro->unsloth) (14.1.0)
Collecting shtab>=1.5.6 (from tyro->unsloth)
  Downloading shtab-1.7.2-py3-none-any.whl.metadata (7.4 kB)
Collecting typeguard>=4.0.0 (from tyro->unsloth)
  Downloading typeguard-4.4.4-py3-none-any.whl.metadata (3.3 kB)
Collecting typing-extensions>=3.7.4.3 (from huggingface_hub>=0.34.0->unsloth)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (3.10.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/site-packages (from requests>=2.32.2->datasets<4.0.0,>=3.4.1->unsloth) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/site-packages (from requests>=2.32.2->datasets<4.0.0,>=3.4.1->unsloth) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/site-packages (from requests>=2.32.2->datasets<4.0.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/site-packages (from requests>=2.32.2->datasets<4.0.0,>=3.4.1->unsloth) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/site-packages (from rich>=11.1.0->tyro->unsloth) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/site-packages (from rich>=11.1.0->tyro->unsloth) (2.19.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/site-packages (from importlib_metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/site-packages (from jinja2->torch>=2.4.0->unsloth) (2.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/site-packages (from pandas->datasets<4.0.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/site-packages (from pandas->datasets<4.0.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/site-packages (from pandas->datasets<4.0.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (1.13.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=11.1.0->tyro->unsloth) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets<4.0.0,>=3.4.1->unsloth) (1.17.0)
Downloading unsloth-2025.9.6-py3-none-any.whl (312 kB)
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
Downloading peft-0.17.1-py3-none-any.whl (504 kB)
Downloading transformers-4.55.4-py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 180.8 MB/s eta 0:00:00
Downloading trl-0.22.2-py3-none-any.whl (544 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 544.8/544.8 kB 189.2 MB/s eta 0:00:00
Downloading unsloth_zoo-2025.9.8-py3-none-any.whl (230 kB)
Downloading xformers-0.0.32.post2-cp39-abi3-manylinux_2_28_x86_64.whl (117.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.2/117.2 MB 137.3 MB/s eta 0:00:00
Downloading bitsandbytes-0.47.0-py3-none-manylinux_2_24_x86_64.whl (61.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 MB 82.9 MB/s eta 0:00:00
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 183.9 MB/s eta 0:00:00
Downloading tyro-0.9.32-py3-none-any.whl (132 kB)
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
Downloading docstring_parser-0.17.0-py3-none-any.whl (36 kB)
Downloading multiprocess-0.70.16-py312-none-any.whl (146 kB)
Downloading pyarrow-21.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (42.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 108.3 MB/s eta 0:00:00
Downloading shtab-1.7.2-py3-none-any.whl (14 kB)
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 195.4 MB/s eta 0:00:00
Downloading typeguard-4.4.4-py3-none-any.whl (34 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading cut_cross_entropy-25.1.1-py3-none-any.whl (22 kB)
Downloading msgspec-0.19.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (213 kB)
Downloading torchao-0.13.0-1-cp39-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 107.4 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
Installing collected packages: torchao, xxhash, typing-extensions, shtab, pyarrow, msgspec, hf_transfer, docstring-parser, dill, typeguard, multiprocess, tyro, tokenizers, xformers, transformers, datasets, cut_cross_entropy, bitsandbytes, trl, peft, unsloth_zoo, unsloth
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.12.2
    Uninstalling typing_extensions-4.12.2:
      Successfully uninstalled typing_extensions-4.12.2
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.0
    Uninstalling tokenizers-0.22.0:
      Successfully uninstalled tokenizers-0.22.0
  Attempting uninstall: transformers
    Found existing installation: transformers 4.56.0
    Uninstalling transformers-4.56.0:
      Successfully uninstalled transformers-4.56.0
Successfully installed bitsandbytes-0.47.0 cut_cross_entropy-25.1.1 datasets-3.6.0 dill-0.3.8 docstring-parser-0.17.0 hf_transfer-0.1.9 msgspec-0.19.0 multiprocess-0.70.16 peft-0.17.1 pyarrow-21.0.0 shtab-1.7.2 tokenizers-0.21.4 torchao-0.13.0 transformers-4.55.4 trl-0.22.2 typeguard-4.4.4 typing-extensions-4.15.0 tyro-0.9.32 unsloth-2025.9.6 unsloth_zoo-2025.9.8 xformers-0.0.32.post2 xxhash-3.5.0

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [3]:
!pip show unsloth

Name: unsloth
Version: 2025.9.6
Summary: 2-5X faster LLM finetuning
Home-page: http://www.unsloth.ai
Author: Unsloth AI team
Author-email: info@unsloth.ai
License:
Location: /usr/local/lib/python3.12/site-packages
Requires: accelerate, bitsandbytes, datasets, diffusers, hf_transfer, huggingface_hub, numpy, packaging, peft, protobuf, psutil, sentencepiece, torch, torchvision, tqdm, transformers, triton, trl, tyro, unsloth_zoo, wheel, xformers
Required-by:

In [4]:
!pip show torch CUDA

WARNING: Package(s) not found: CUDA
Name: torch
Version: 2.8.0+cu129
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /usr/local/lib/python3.12/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-cufile-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, setuptools, sympy, triton, typing-extensions
Required-by: accelerate, bitsandbytes, cut-cross-entropy, peft, torchaudio, torchvision, unsloth, unsloth_zoo, xformers

In [6]:
!pip install wandb
import wandb # for experiment tracking

Collecting wandb
  Downloading wandb-0.22.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.12/site-packages (from wandb) (8.2.1)
Collecting gitpython!=3.1.29,>=1.0.0 (from wandb)
  Downloading gitpython-3.1.45-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/site-packages (from wandb) (25.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/site-packages (from wandb) (4.4.0)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /usr/local/lib/python3.12/site-packages (from wandb) (5.29.2)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.12/site-packages (from wandb) (2.11.7)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/site-packages (from wandb) (6.0.2)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/site-packages (from wandb) (2.32.5)
Collecting sentry-sdk>=2.0.0 (from wandb)
  Downloading sentry_sdk-2.38.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.12/site-packages (from wandb) (4.15.0)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.29,>=1.0.0->wandb)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/site-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/site-packages (from pydantic<3->wandb) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/site-packages (from pydantic<3->wandb) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/site-packages (from requests<3,>=2.0.0->wandb) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/site-packages (from requests<3,>=2.0.0->wandb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/site-packages (from requests<3,>=2.0.0->wandb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/site-packages (from requests<3,>=2.0.0->wandb) (2024.8.30)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb)
  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Downloading wandb-0.22.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.6/19.6 MB 154.7 MB/s eta 0:00:00
Downloading gitpython-3.1.45-py3-none-any.whl (208 kB)
Downloading sentry_sdk-2.38.0-py2.py3-none-any.whl (370 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading smmap-5.0.2-py3-none-any.whl (24 kB)
Installing collected packages: smmap, sentry-sdk, gitdb, gitpython, wandb
Successfully installed gitdb-4.0.12 gitpython-3.1.45 sentry-sdk-2.38.0 smmap-5.0.2 wandb-0.22.0

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [7]:
!pip show huggingface_hub

Name: huggingface-hub
Version: 0.34.4
Summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
Home-page: https://github.com/huggingface/huggingface_hub
Author: Hugging Face, Inc.
Author-email: julien@huggingface.co
License: Apache
Location: /usr/local/lib/python3.12/site-packages
Requires: filelock, fsspec, hf-xet, packaging, pyyaml, requests, tqdm, typing-extensions
Required-by: accelerate, datasets, diffusers, peft, tokenizers, transformers, unsloth, unsloth_zoo

In [5]:
!pip show wandb

WARNING: Package(s) not found: wandb

In [8]:
!pip show trl

Name: trl
Version: 0.22.2
Summary: Train transformer language models with reinforcement learning.
Home-page: https://github.com/huggingface/trl
Author: Leandro von Werra
Author-email: leandro.vonwerra@gmail.com
License:
Location: /usr/local/lib/python3.12/site-packages
Requires: accelerate, datasets, transformers
Required-by: unsloth, unsloth_zoo

In [9]:
print(os.cpu_count())
print(torch.cuda.device_count())

43
1

In [10]:
from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template
import torch
from trl import SFTTrainer, SFTConfig
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
import os
import wandb
from huggingface_hub import login
from dotenv import load_dotenv

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

In [ ]:
!hf auth login --token hf_token
!hf auth whoami

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `hf`CLI if you want to set the git credential as well.
Token is valid (permission: write).
The token `thesis_token` has been saved to /root/.cache/huggingface/stored_tokens
Your token has been saved to /root/.cache/huggingface/token
Login successful.
The current active token is: `thesis_token`
kunjanshah

In [12]:
dataset = load_dataset("kunjanshah/new_multi_turn_function_calling_split")

README.md:   0%|          | 0.00/997 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/496k [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/128k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/122k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/320 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/40 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/40 [00:00<?, ? examples/s]

In [13]:
dataset['train'][0]['Conversation']

'[\n  {\n    "role": "system",\n    "content": "<instructions>\\nYou are an AI assistant with access to a set of tools. Your goal is to accurately and helpfully respond to user queries.\\n\\n**Workflow:**\\n\\n1. **Understand Query:** Analyze the user\'s request and their intent.\\n2. **Decide Tool Use:**\\n    * If you can answer directly from your knowledge, do so.\\n    * If external info/action is needed, use a tool.\\n3. **Select & Extract Tool Inputs:** \\n    * Choose the best tool from `Available Tools`.\\n    * Identify all required parameters from the query.\\n    * Use default values from the tool specification for any fields not explicitly mentioned by the user.\\n    * **Always include default values in the tool call, even if the user did not mention them.**\\n    * Don\'t make assumptions beyond what\'s in the query or default values.\\n4. **Execute Tool (Output Format):**\\n    * **If you have all required parameters (from user input or defaults), immediately make the tool call.**\\n    * **Do not ask for missing optional parameters - use defaults.**\\n    * **Only ask for clarification if absolutely required parameters are missing.**\\n    * **Once you receive the missing required parameters, immediately make the tool call without further questions.**\\n    * **If a tool is needed, output the tool call wrapped in `<tool_call>` tags.**\\n    * **The content within `<tool_call>` MUST be a JSON object containing `name` and `arguments`.**\\n    * **Format:**\\n     ```json\\n     <tool_call>\\n     {\\"name\\": \\"exact_tool_name\\", \\"arguments\\": {\\"arg_name1\\": \\"value1\\", \\"arg_name2\\": \\"value2\\"}}\\n     </tool_call>\\n     ```\\n</instructions>\\nHere are the available tools:\\n<tools>\\n[{\\"type\\": \\"function\\",\\"function\\": {\\"name\\": \\"update_inventory_count\\",\\"description\\": \\"Update product inventory quantity\\",\\"parameters\\": {\\"type\\": \\"object\\",\\"properties\\": {\\"product_id\\": {\\"type\\": \\"string\\",\\"description\\": \\"Product identifier\\"},\\"quantity_change\\": {\\"type\\": \\"integer\\",\\"description\\": \\"Quantity delta (positive/negative)\\"},\\"reason\\": {\\"type\\": \\"string\\",\\"enum\\": [\\"sale\\",\\"purchase\\",\\"return\\",\\"damage\\",\\"adjustment\\"],\\"description\\": \\"Change reason\\"},\\"updated_by\\": {\\"type\\": \\"string\\",\\"description\\": \\"Employee ID performing update\\"}},\\"required\\": [\\"product_id\\",\\"quantity_change\\",\\"reason\\",\\"updated_by\\"]}}},{\\"type\\": \\"function\\",\\"function\\": {\\"name\\": \\"create_performance_review\\",\\"description\\": \\"Create a performance review for an employee.\\",\\"parameters\\": {\\"type\\": \\"object\\",\\"properties\\": {\\"employee_id\\": {\\"type\\": \\"string\\",\\"description\\": \\"ID of the employee being reviewed\\"},\\"reviewer_id\\": {\\"type\\": \\"string\\",\\"description\\": \\"ID of the reviewer (manager/supervisor)\\"},\\"review_period\\": {\\"type\\": \\"object\\",\\"properties\\": {\\"start_date\\": {\\"type\\": \\"string\\",\\"description\\": \\"Review period start date (YYYY-MM-DD)\\"},\\"end_date\\": {\\"type\\": \\"string\\",\\"description\\": \\"Review period end date (YYYY-MM-DD)\\"}},\\"required\\": [\\"start_date\\",\\"end_date\\"]},\\"overall_rating\\": {\\"type\\": \\"integer\\",\\"description\\": \\"Performance rating (1-5 scale)\\",\\"minimum\\": 1,\\"maximum\\": 5},\\"review_type\\": {\\"type\\": \\"string\\",\\"enum\\": [\\"annual\\",\\"mid_year\\",\\"quarterly\\",\\"probationary\\"],\\"description\\": \\"Type of review\\"}},\\"required\\": [\\"employee_id\\",\\"reviewer_id\\",\\"review_period\\",\\"overall_rating\\"]}}},{\\"type\\": \\"function\\",\\"function\\": {\\"name\\": \\"conduct_compliance_audit\\",\\"description\\": \\"Execute a compliance audit with risk assessment and reporting.\\",\\"parameters\\": {\\"type\\": \\"object\\",\\"properties\\": {\\"audit_id\\": {\\"type\\": \\"string\\",\\"description\\": \\"Unique identifier for the audit\\"},\\"regulatory_frameworks\\": {\\"type\\": \\"array\\",\\"items\\": {\\"type\\": \\"string\\",\\"enum\\": [\\"GDPR\\",\\"HIPAA\\",\\"SOX\\",\\"PCI_DSS\\",\\"ISO_27001\\",\\"CCPA\\",\\"SOC2\\",\\"FISMA\\"]},\\"description\\": \\"Frameworks to audit against\\"},\\"business_units\\": {\\"type\\": \\"array\\",\\"items\\": {\\"type\\": \\"string\\"},\\"description\\": \\"Business units to include\\"},\\"audit_period\\": {\\"type\\": \\"object\\",\\"properties\\": {\\"start_date\\": {\\"type\\": \\"string\\",\\"description\\": \\"Audit start date (YYYY-MM-DD)\\"},\\"end_date\\": {\\"type\\": \\"string\\",\\"description\\": \\"Audit end date (YYYY-MM-DD)\\"}},\\"required\\": [\\"start_date\\",\\"end_date\\"]},\\"lead_auditor\\": {\\"type\\": \\"string\\",\\"description\\": \\"Employee ID of lead auditor\\"},\\"risk_categories\\": {\\"type\\": \\"array\\",\\"items\\": {\\"type\\": \\"string\\",\\"enum\\": [\\"data_privacy\\",\\"financial_reporting\\",\\"operational\\",\\"security\\",\\"environmental\\",\\"employment\\"]},\\"description\\": \\"Risk categories to evaluate\\"},\\"materiality_threshold\\": {\\"type\\": \\"number\\",\\"description\\": \\"Financial materiality threshold\\"},\\"automated_testing\\": {\\"type\\": \\"boolean\\",\\"default\\": true,\\"description\\": \\"Enable automated testing\\"}},\\"required\\": [\\"audit_id\\",\\"regulatory_frameworks\\",\\"business_units\\",\\"audit_period\\",\\"lead_auditor\\",\\"risk_categories\\"]}}}]\\n</tools>"\n  },\n  {\n    "role": "user",\n    "content": "I need to update inventory. We sold 15 units today, so please reduce the count by 15 and mark it as a sale. Updated by EMP002."\n  },\n  {\n    "role": "assistant",\n    "content": "Sure—what’s the product ID for the item you want to update? Once I have that, I’ll reduce the inventory by 15, mark the reason as “sale,” and note it was updated by EMP002."\n  },\n  {\n    "role": "user",\n    "content": "The product_id is PROD001."\n  },\n  {\n    "role": "assistant",\n    "content": "<tool_call>[\\n  {\\n    \\"name\\": \\"update_inventory_count\\",\\n    \\"arguments\\": {\\n      \\"product_id\\": \\"PROD001\\",\\n      \\"quantity_change\\": -15,\\n      \\"reason\\": \\"sale\\",\\n      \\"updated_by\\": \\"EMP002\\"\\n    }\\n  }\\n]</tool_call>"\n  }\n]'

In [14]:
# Applying Chat Templates with Unsloth
from unsloth.chat_templates import CHAT_TEMPLATES
print(list(CHAT_TEMPLATES.keys()))
print()
# print(CHAT_TEMPLAES['llama-3.2']
print(CHAT_TEMPLATES['qwen3'])

['unsloth', 'zephyr', 'chatml', 'mistral', 'llama', 'vicuna', 'vicuna_old', 'vicuna old', 'alpaca', 'gemma', 'gemma_chatml', 'gemma2', 'gemma2_chatml', 'llama-3', 'llama3', 'phi-3', 'phi-35', 'phi-3.5', 'llama-3.1', 'llama-31', 'llama-3.2', 'llama-3.3', 'llama-32', 'llama-33', 'qwen-2.5', 'qwen-25', 'qwen25', 'qwen2.5', 'phi-4', 'gemma-3', 'gemma3', 'qwen-3', 'qwen3', 'gemma-3n', 'gemma3n', 'gpt-oss', 'gptoss', 'qwen3-instruct', 'qwen3-thinking']

('\n{%- if tools %}\n    {{- \'<|im_start|>system\n\' }}\n    {%- if messages[0].role == \'system\' %}\n        {{- messages[0].content + \'\n\n\' }}\n    {%- endif %}\n    {{- "# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}\n    {%- for tool in tools %}\n        {{- "\n" }}\n        {{- tool | tojson }}\n    {%- endfor %}\n    {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{\\"name\\": <function-name>, \\"arguments\\": <args-json-object>}\n</tool_call><|im_end|>\n" }}\n{%- else %}\n    {%- if messages[0].role == \'system\' %}\n        {{- \'<|im_start|>system\n\' + messages[0].content + \'<|im_end|>\n\' }}\n    {%- endif %}\n{%- endif %}\n{%- set ns = namespace(multi_step_tool=true, last_query_index=messages|length - 1) %}\n{%- for forward_message in messages %}\n    {%- set index = (messages|length - 1) - loop.index0 %}\n    {%- set message = messages[index] %}\n    {%- set current_content = message.content if message.content is not none else \'\' %}\n    {%- set tool_start = \'<tool_response>\' %}\n    {%- set tool_start_length = tool_start|length %}\n    {%- set start_of_message = current_content[:tool_start_length] %}\n    {%- set tool_end = \'</tool_response>\' %}\n    {%- set tool_end_length = tool_end|length %}\n    {%- set start_pos = (current_content|length) - tool_end_length %}\n    {%- if start_pos < 0 %}\n        {%- set start_pos = 0 %}\n    {%- endif %}\n    {%- set end_of_message = current_content[start_pos:] %}\n    {%- if ns.multi_step_tool and message.role == "user" and not(start_of_message == tool_start and end_of_message == tool_end) %}\n        {%- set ns.multi_step_tool = false %}\n        {%- set ns.last_query_index = index %}\n    {%- endif %}\n{%- endfor %}\n{%- for message in messages %}\n    {%- if (message.role == "user") or (message.role == "system" and not loop.first) %}\n        {{- \'<|im_start|>\' + message.role + \'\n\' + message.content + \'<|im_end|>\' + \'\n\' }}\n    {%- elif message.role == "assistant" %}\n        {%- set content = message.content %}\n        {%- set reasoning_content = \'\' %}\n        {%- if message.reasoning_content is defined and message.reasoning_content is not none %}\n            {%- set reasoning_content = message.reasoning_content %}\n        {%- else %}\n            {%- if \'</think>\' in message.content %}\n                {%- set content = (message.content.split(\'</think>\')|last).lstrip(\'\n\') %}\n                {%- set reasoning_content = (message.content.split(\'</think>\')|first).rstrip(\'\n\') %}\n                {%- set reasoning_content = (reasoning_content.split(\'<think>\')|last).lstrip(\'\n\') %}\n            {%- endif %}\n        {%- endif %}\n        {%- if loop.index0 > ns.last_query_index %}\n            {%- if loop.last or (not loop.last and reasoning_content) %}\n                {{- \'<|im_start|>\' + message.role + \'\n<think>\n\' + reasoning_content.strip(\'\n\') + \'\n</think>\n\n\' + content.lstrip(\'\n\') }}\n            {%- else %}\n                {{- \'<|im_start|>\' + message.role + \'\n\' + content }}\n            {%- endif %}\n        {%- else %}\n            {{- \'<|im_start|>\' + message.role + \'\n\' + content }}\n        {%- endif %}\n        {%- if message.tool_calls %}\n            {%- for tool_call in message.tool_calls %}\n                {%- if (loop.first and content) or (not loop.first) %}\n                    {{- \'\n\' }}\n                {%- endif %}\n                {%- if tool_call.function %}\n                    {%- set tool_call = tool_call.function %}\n                {%- endif %}\n                {{- \'<tool_call>\n{"name": "\' }}\n                {{- tool_call.name }}\n                {{- \'", "arguments": \' }}\n                {%- if tool_call.arguments is string %}\n                    {{- tool_call.arguments }}\n                {%- else %}\n                    {{- tool_call.arguments | tojson }}\n                {%- endif %}\n                {{- \'}\n</tool_call>\' }}\n            {%- endfor %}\n        {%- endif %}\n        {{- \'<|im_end|>\n\' }}\n    {%- elif message.role == "tool" %}\n        {%- if loop.first or (messages[loop.index0 - 1].role != "tool") %}\n            {{- \'<|im_start|>user\' }}\n        {%- endif %}\n        {{- \'\n<tool_response>\n\' }}\n        {{- message.content }}\n        {{- \'\n</tool_response>\' }}\n        {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}\n            {{- \'<|im_end|>\n\' }}\n        {%- endif %}\n    {%- endif %}\n{%- endfor %}\n{%- if add_generation_prompt %}\n    {{- \'<|im_start|>assistant\n\' }}\n    {%- if enable_thinking is defined and enable_thinking is false %}\n        {{- \'<think>\n\n</think>\n\n\' }}\n    {%- endif %}\n{%- endif %}\n', '<|im_end|>', False, '\nFROM {__FILE_LOCATION__}\nTEMPLATE """{{- if .Messages }}\n{{- if or .System .Tools }}<|im_start|>system\n{{- if .System }}\n{{ .System }}\n{{- end }}\n{{- if .Tools }}\n\n# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>\n{{- range .Tools }}\n{"type": "function", "function": {{ .Function }}}\n{{- end }}\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{"name": <function-name>, "arguments": <args-json-object>}\n</tool_call>\n{{- end }}<|im_end|>\n{{ end }}\n{{- range $i, $_ := .Messages }}\n{{- $last := eq (len (slice $.Messages $i)) 1 -}}\n{{- if eq .Role "user" }}<|im_start|>user\n{{ .Content }}<|im_end|>\n{{ else if eq .Role "assistant" }}<|im_start|>assistant\n{{ if .Content }}{{ .Content }}\n{{- else if .ToolCalls }}<tool_call>\n{{ range .ToolCalls }}{"name": "{{ .Function.Name }}", "arguments": {{ .Function.Arguments }}}\n{{ end }}</tool_call>\n{{- end }}{{ if not $last }}<|im_end|>\n{{ end }}\n{{- else if eq .Role "tool" }}<|im_start|>user\n<tool_response>\n{{ .Content }}\n</tool_response><|im_end|>\n{{ end }}\n{{- if and (ne .Role "assistant") $last }}<|im_start|>assistant\n{{ end }}\n{{- end }}\n{{- else }}\n{{- if .System }}<|im_start|>system\n{{ .System }}<|im_end|>\n{{ end }}{{ if .Prompt }}<|im_start|>user\n{{ .Prompt }}<|im_end|>\n{{ end }}<|im_start|>assistant\n{{ end }}{{ .Response }}{{ if .Response }}<|im_end|>{{ end }}"""\nPARAMETER stop "<|im_end|>"\nPARAMETER stop "<|im_start|>"\nPARAMETER temperature 0.6\nPARAMETER min_p 0.0\nPARAMETER top_k 20\nPARAMETER top_p 0.95\nPARAMETER repeat_penalty 1\n')

<details> <summary>📘 <strong>1. Alpaca Format</strong></summary>
### Instruction:
What is the capital of France?

### Response:
Paris is the capital of France.

</details> <details> <summary>📗 <strong>2. ShareGPT Format</strong></summary>
[
  {"from": "human", "value": "What is the capital of France?"},
  {"from": "gpt", "value": "Paris is the capital of France."}
]

</details> <details> <summary>📙 <strong>3. ChatML Format (OpenAI Style)</strong></summary>
<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
What is the capital of France?<|im_end|>
<|im_start|>assistant
Paris is the capital of France.<|im_end|>

</details> <details> <summary>📕 <strong>4. LLaMA-3.2 Format (Meta)</strong></summary>
<|begin_of_text|>
<|start_header_id|>system<|end_header_id|>
You are a helpful assistant.<|eot_id|>
<|start_header_id|>user<|end_header_id|>
What is the capital of France?<|eot_id|>
<|start_header_id|>assistant<|end_header_id|>
Paris is the capital of France.<|eot_id|>

</details>
<details> <summary>📌 Difference between Llama template vs ChatML</summary>

Markers:

ChatML = <|im_start|> / <|im_end|>

Llama = <|start_header_id|> / <|eot_id|>

Token IDs: totally different — Llama tokenizer expects its own IDs.

Training: Llama Instruct models were fine-tuned with the Llama template, not ChatML.

👉 If you feed a Llama model ChatML style (<|im_start|>), the tokenizer will just see normal text tokens, not special “role” tokens. That breaks consistency.

📌 So how to think of it

Alpaca, ShareGPT → early formats, not universal.

ChatML → became a standard in many OpenAI datasets.

Llama template → Meta’s own “ChatML-like” structure, but with different special tokens.

Other variants (Vicuna, Gemma, Zephyr, etc.) → each has their own templates, usually forks of ChatML or Llama style.

✅ In practice:

If your model is Llama-3.2, use the Llama-3.2 template.

Don’t mix ChatML unless you have a conversion step that maps <|im_start|> → <|start_header_id|> etc.

Templates matter because they decide where loss is masked, which tokens mark roles, and how inference behaves.</details>

In [15]:
model, tokenizer = FastLanguageModel.from_pretrained(model_name="unsloth/Qwen3-14B-unsloth-bnb-4bit", max_seq_length=2048, load_in_4bit=True, dtype=None, device_map='auto')
print("Model:", model)
#print("Tokenizer:", tokenizer)
print("Number of parameters:", model.num_parameters())
#model.print_trainable_parameters()

==((====))==  Unsloth 2025.9.6: Fast Qwen3 patching. Transformers: 4.55.4.
   \\   /|    NVIDIA A100 80GB PCIe. Num GPUs = 1. Max memory: 79.252 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu129. CUDA: 8.0. CUDA Toolkit: 12.9. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.32.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.59G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/1.56G [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Model: Qwen3ForCausalLM(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 5120, padding_idx=151654)
    (layers): ModuleList(
      (0-5): 6 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear4bit(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (6): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (7-18): 12 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear4bit(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (19): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (20-37): 18 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear4bit(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (38): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (39): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear4bit(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((5120,), eps=1e-06)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=5120, out_features=151936, bias=False)
)
Number of parameters: 14768307200

<details>
<summary> 🚀 Why is device mapping 0?</summary>

That’s normal.

`device_map={'': 0}` means Hugging Face automatically put the **whole model** on **device 0 (cuda:0)**.

- The key (`''`) is blank because it’s the root of the model (not split into layers).  
- The value (`0`) means GPU index 0.  

If you had multiple GPUs and used `device_map="auto"`, you’d see entries like:

```python
{'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 1, ...}
showing layer sharding across GPUs.

Since you only have one GPU (or auto-detection decided to keep it on one), it just maps everything to device 0.

👉 So, Device mapping: {'': 0} = “entire model sits on cuda:0.”

</details> ```

In [16]:
print("Model object:", model)
print("\nModel config:", model.config)
print("\nModel Parameter:", model.num_parameters())
print("dtype:", model.dtype)           # expect torch.float16 compute
print("device:", next(model.parameters()).device)
print("Device mapping:" , model.hf_device_map)
print("Model is on:", next(model.parameters()).device)
print("\nTokenizer object:", tokenizer)
print("Tokenizer name:", tokenizer.name_or_path)
print("\nTokenizer vocabulary size:", tokenizer.vocab_size)
print("\nTokenizer special tokens:", tokenizer.special_tokens_map)
print("EOS id:", tokenizer.eos_token_id)
print("PAD id:", tokenizer.pad_token_id)

Model object: Qwen3ForCausalLM(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 5120, padding_idx=151654)
    (layers): ModuleList(
      (0-5): 6 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear4bit(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (6): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (7-18): 12 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear4bit(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (19): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (20-37): 18 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear4bit(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (38): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
      (39): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (k_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=5120, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (up_proj): Linear4bit(in_features=5120, out_features=17408, bias=False)
          (down_proj): Linear4bit(in_features=17408, out_features=5120, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((5120,), eps=1e-06)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=5120, out_features=151936, bias=False)
)

Model config: Qwen3Config {
  "architectures": [
    "Qwen3ForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "head_dim": 128,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 17408,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 40960,
  "max_window_layers": 40,
  "model_type": "qwen3",
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "num_key_value_heads": 8,
  "pad_token_id": 151654,
  "quantization_config": {
    "bnb_4bit_compute_dtype": "bfloat16",
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_use_double_quant": true,
    "llm_int8_enable_fp32_cpu_offload": false,
    "llm_int8_has_fp16_weight": false,
    "llm_int8_skip_modules": null,
    "llm_int8_threshold": 6.0,
    "load_in_4bit": true,
    "load_in_8bit": false,
    "quant_method": "bitsandbytes"
  },
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000,
  "sliding_window": null,
  "tie_word_embeddings": false,
  "transformers_version": "4.56.1",
  "unsloth_fixed": true,
  "unsloth_version": "2025.9.4",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}


Model Parameter: 14768307200
dtype: torch.bfloat16
device: cuda:0
Device mapping: {'': 0}
Model is on: cuda:0

Tokenizer object: Qwen2TokenizerFast(name_or_path='unsloth/Qwen3-14B-unsloth-bnb-4bit', vocab_size=151643, model_max_length=40960, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'eos_token': '<|im_end|>', 'pad_token': '<|vision_pad|>', 'additional_special_tokens': ['<|im_start|>', '<|im_end|>', '<|object_ref_start|>', '<|object_ref_end|>', '<|box_start|>', '<|box_end|>', '<|quad_start|>', '<|quad_end|>', '<|vision_start|>', '<|vision_end|>', '<|vision_pad|>', '<|image_pad|>', '<|video_pad|>']}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	151643: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151644: AddedToken("<|im_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151645: AddedToken("<|im_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151646: AddedToken("<|object_ref_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151647: AddedToken("<|object_ref_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151648: AddedToken("<|box_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151649: AddedToken("<|box_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151650: AddedToken("<|quad_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151651: AddedToken("<|quad_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151652: AddedToken("<|vision_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151653: AddedToken("<|vision_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151654: AddedToken("<|vision_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151655: AddedToken("<|image_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151656: AddedToken("<|video_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151657: AddedToken("<tool_call>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151658: AddedToken("</tool_call>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151659: AddedToken("<|fim_prefix|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151660: AddedToken("<|fim_middle|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151661: AddedToken("<|fim_suffix|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151662: AddedToken("<|fim_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151663: AddedToken("<|repo_name|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151664: AddedToken("<|file_sep|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151665: AddedToken("<tool_response>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151666: AddedToken("</tool_response>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151667: AddedToken("<think>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151668: AddedToken("</think>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
}
)
Tokenizer name: unsloth/Qwen3-14B-unsloth-bnb-4bit

Tokenizer vocabulary size: 151643

Tokenizer special tokens: {'eos_token': '<|im_end|>', 'pad_token': '<|vision_pad|>', 'additional_special_tokens': ['<|im_start|>', '<|im_end|>', '<|object_ref_start|>', '<|object_ref_end|>', '<|box_start|>', '<|box_end|>', '<|quad_start|>', '<|quad_end|>', '<|vision_start|>', '<|vision_end|>', '<|vision_pad|>', '<|image_pad|>', '<|video_pad|>']}
EOS id: 151645
PAD id: 151654

In [17]:
print("Chat template available:", hasattr(tokenizer, "chat_template"))
print("Chat template:", getattr(tokenizer, "chat_template", None))

Chat template available: True
Chat template: {%- if tools %}
    {{- '<|im_start|>system\n' }}
    {%- if messages[0].role == 'system' %}
        {{- messages[0].content + '\n\n' }}
    {%- endif %}
    {{- "# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}
    {%- for tool in tools %}
        {{- "\n" }}
        {{- tool | tojson }}
    {%- endfor %}
    {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{\"name\": <function-name>, \"arguments\": <args-json-object>}\n</tool_call><|im_end|>\n" }}
{%- else %}
    {%- if messages[0].role == 'system' %}
        {{- '<|im_start|>system\n' + messages[0].content + '<|im_end|>\n' }}
    {%- endif %}
{%- endif %}
{%- set ns = namespace(multi_step_tool=true, last_query_index=messages|length - 1) %}
{%- for forward_message in messages %}
    {%- set index = (messages|length - 1) - loop.index0 %}
    {%- set message = messages[index] %}
    {%- set tool_start = '<tool_response>' %}
    {%- set tool_start_length = tool_start|length %}
    {%- set start_of_message = message.content[:tool_start_length] %}
    {%- set tool_end = '</tool_response>' %}
    {%- set tool_end_length = tool_end|length %}
    {%- set start_pos = (message.content|length) - tool_end_length %}
    {%- if start_pos < 0 %}
        {%- set start_pos = 0 %}
    {%- endif %}
    {%- set end_of_message = message.content[start_pos:] %}
    {%- if ns.multi_step_tool and message.role == "user" and not(start_of_message == tool_start and end_of_message == tool_end) %}
        {%- set ns.multi_step_tool = false %}
        {%- set ns.last_query_index = index %}
    {%- endif %}
{%- endfor %}
{%- for message in messages %}
    {%- if (message.role == "user") or (message.role == "system" and not loop.first) %}
        {{- '<|im_start|>' + message.role + '\n' + message.content + '<|im_end|>' + '\n' }}
    {%- elif message.role == "assistant" %}
        {%- set content = message.content %}
        {%- set reasoning_content = '' %}
        {%- if message.reasoning_content is defined and message.reasoning_content is not none %}
            {%- set reasoning_content = message.reasoning_content %}
        {%- else %}
            {%- if '</think>' in message.content %}
                {%- set content = (message.content.split('</think>')|last).lstrip('\n') %}
                {%- set reasoning_content = (message.content.split('</think>')|first).rstrip('\n') %}
                {%- set reasoning_content = (reasoning_content.split('<think>')|last).lstrip('\n') %}
            {%- endif %}
        {%- endif %}
        {%- if loop.index0 > ns.last_query_index %}
            {%- if loop.last or (not loop.last and reasoning_content) %}
                {{- '<|im_start|>' + message.role + '\n<think>\n' + reasoning_content.strip('\n') + '\n</think>\n\n' + content.lstrip('\n') }}
            {%- else %}
                {{- '<|im_start|>' + message.role + '\n' + content }}
            {%- endif %}
        {%- else %}
            {{- '<|im_start|>' + message.role + '\n' + content }}
        {%- endif %}
        {%- if message.tool_calls %}
            {%- for tool_call in message.tool_calls %}
                {%- if (loop.first and content) or (not loop.first) %}
                    {{- '\n' }}
                {%- endif %}
                {%- if tool_call.function %}
                    {%- set tool_call = tool_call.function %}
                {%- endif %}
                {{- '<tool_call>\n{"name": "' }}
                {{- tool_call.name }}
                {{- '", "arguments": ' }}
                {%- if tool_call.arguments is string %}
                    {{- tool_call.arguments }}
                {%- else %}
                    {{- tool_call.arguments | tojson }}
                {%- endif %}
                {{- '}\n</tool_call>' }}
            {%- endfor %}
        {%- endif %}
        {{- '<|im_end|>\n' }}
    {%- elif message.role == "tool" %}
        {%- if loop.first or (messages[loop.index0 - 1].role != "tool") %}
            {{- '<|im_start|>user' }}
        {%- endif %}
        {{- '\n<tool_response>\n' }}
        {{- message.content }}
        {{- '\n</tool_response>' }}
        {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}
            {{- '<|im_end|>\n' }}
        {%- endif %}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n' }}
    {%- if enable_thinking is defined and enable_thinking is false %}
        {{- '<think>\n\n</think>\n\n' }}
    {%- endif %}
{%- endif %}

In [17]:
# model = FastLanguageModel.get_peft_model(
#     model,
#     r=16,
#     lora_alpha=16,
#     lora_dropout=0.00,
#     target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
#     use_gradient_checkpointing="unsloth",
#     use_rslora = False,
#     bias="none",
#     loftq_config = None
#     )
# print(model)

Unsloth 2025.9.4 patched 40 layers with 40 QKV layers, 40 O layers and 40 MLP layers.

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen3ForCausalLM(
      (model): Qwen3Model(
        (embed_tokens): Embedding(151936, 5120, padding_idx=151654)
        (layers): ModuleList(
          (0-5): 6 x Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=17408, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=17408, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
          )
          (6): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear(
                (base_layer): Linear(in_features=17408, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=17408, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
          )
          (7-18): 12 x Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=17408, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=17408, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
          )
          (19): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )

In [18]:
# model.print_trainable_parameters()
# only_lora = all("lora_" in n for n,p in model.named_parameters() if p.requires_grad)
# print("Only LoRA params trainable:", only_lora)
# for name, param in model.named_parameters():
#     print(name, param.requires_grad)

trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330
Only LoRA params trainable: True
base_model.model.model.embed_tokens.weight False
base_model.model.model.layers.0.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.0.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.0.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.0.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.0.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.0.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.0.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.0.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.0.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.0.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.0.self_attn.q_norm.weight False
base_model.model.model.layers.0.self_attn.k_norm.weight False
base_model.model.model.layers.0.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.0.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.0.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.0.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.0.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.0.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.0.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.0.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.0.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.0.input_layernorm.weight False
base_model.model.model.layers.0.post_attention_layernorm.weight False
base_model.model.model.layers.1.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.1.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.1.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.1.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.1.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.1.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.1.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.1.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.1.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.1.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.1.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.1.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.1.self_attn.q_norm.weight False
base_model.model.model.layers.1.self_attn.k_norm.weight False
base_model.model.model.layers.1.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.1.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.1.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.1.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.1.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.1.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.1.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.1.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.1.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.1.input_layernorm.weight False
base_model.model.model.layers.1.post_attention_layernorm.weight False
base_model.model.model.layers.2.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.2.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.2.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.2.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.2.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.2.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.2.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.2.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.2.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.2.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.2.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.2.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.2.self_attn.q_norm.weight False
base_model.model.model.layers.2.self_attn.k_norm.weight False
base_model.model.model.layers.2.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.2.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.2.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.2.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.2.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.2.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.2.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.2.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.2.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.2.input_layernorm.weight False
base_model.model.model.layers.2.post_attention_layernorm.weight False
base_model.model.model.layers.3.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.3.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.3.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.3.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.3.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.3.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.3.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.3.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.3.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.3.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.3.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.3.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.3.self_attn.q_norm.weight False
base_model.model.model.layers.3.self_attn.k_norm.weight False
base_model.model.model.layers.3.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.3.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.3.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.3.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.3.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.3.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.3.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.3.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.3.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.3.input_layernorm.weight False
base_model.model.model.layers.3.post_attention_layernorm.weight False
base_model.model.model.layers.4.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.4.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.4.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.4.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.4.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.4.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.4.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.4.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.4.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.4.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.4.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.4.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.4.self_attn.q_norm.weight False
base_model.model.model.layers.4.self_attn.k_norm.weight False
base_model.model.model.layers.4.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.4.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.4.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.4.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.4.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.4.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.4.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.4.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.4.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.4.input_layernorm.weight False
base_model.model.model.layers.4.post_attention_layernorm.weight False
base_model.model.model.layers.5.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.5.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.5.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.5.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.5.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.5.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.5.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.5.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.5.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.5.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.5.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.5.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.5.self_attn.q_norm.weight False
base_model.model.model.layers.5.self_attn.k_norm.weight False
base_model.model.model.layers.5.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.5.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.5.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.5.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.5.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.5.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.5.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.5.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.5.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.5.input_layernorm.weight False
base_model.model.model.layers.5.post_attention_layernorm.weight False
base_model.model.model.layers.6.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.6.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.6.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.6.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.6.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.6.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.6.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.6.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.6.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.6.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.6.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.6.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.6.self_attn.q_norm.weight False
base_model.model.model.layers.6.self_attn.k_norm.weight False
base_model.model.model.layers.6.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.6.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.6.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.6.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.6.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.6.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.6.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.6.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.6.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.6.input_layernorm.weight False
base_model.model.model.layers.6.post_attention_layernorm.weight False
base_model.model.model.layers.7.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.7.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.7.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.7.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.7.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.7.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.7.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.7.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.7.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.7.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.7.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.7.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.7.self_attn.q_norm.weight False
base_model.model.model.layers.7.self_attn.k_norm.weight False
base_model.model.model.layers.7.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.7.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.7.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.7.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.7.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.7.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.7.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.7.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.7.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.7.input_layernorm.weight False
base_model.model.model.layers.7.post_attention_layernorm.weight False
base_model.model.model.layers.8.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.8.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.8.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.8.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.8.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.8.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.8.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.8.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.8.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.8.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.8.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.8.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.8.self_attn.q_norm.weight False
base_model.model.model.layers.8.self_attn.k_norm.weight False
base_model.model.model.layers.8.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.8.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.8.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.8.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.8.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.8.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.8.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.8.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.8.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.8.input_layernorm.weight False
base_model.model.model.layers.8.post_attention_layernorm.weight False
base_model.model.model.layers.9.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.9.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.9.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.9.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.9.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.9.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.9.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.9.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.9.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.9.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.9.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.9.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.9.self_attn.q_norm.weight False
base_model.model.model.layers.9.self_attn.k_norm.weight False
base_model.model.model.layers.9.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.9.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.9.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.9.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.9.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.9.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.9.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.9.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.9.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.9.input_layernorm.weight False
base_model.model.model.layers.9.post_attention_layernorm.weight False
base_model.model.model.layers.10.self_attn.q_proj.base_layer.weight False
base_model.model.model.layers.10.self_attn.q_proj.lora_A.default.weight True
base_model.model.model.layers.10.self_attn.q_proj.lora_B.default.weight True
base_model.model.model.layers.10.self_attn.k_proj.base_layer.weight False
base_model.model.model.layers.10.self_attn.k_proj.lora_A.default.weight True
base_model.model.model.layers.10.self_attn.k_proj.lora_B.default.weight True
base_model.model.model.layers.10.self_attn.v_proj.base_layer.weight False
base_model.model.model.layers.10.self_attn.v_proj.lora_A.default.weight True
base_model.model.model.layers.10.self_attn.v_proj.lora_B.default.weight True
base_model.model.model.layers.10.self_attn.o_proj.base_layer.weight False
base_model.model.model.layers.10.self_attn.o_proj.lora_A.default.weight True
base_model.model.model.layers.10.self_attn.o_proj.lora_B.default.weight True
base_model.model.model.layers.10.self_attn.q_norm.weight False
base_model.model.model.layers.10.self_attn.k_norm.weight False
base_model.model.model.layers.10.mlp.gate_proj.base_layer.weight False
base_model.model.model.layers.10.mlp.gate_proj.lora_A.default.weight True
base_model.model.model.layers.10.mlp.gate_proj.lora_B.default.weight True
base_model.model.model.layers.10.mlp.up_proj.base_layer.weight False
base_model.model.model.layers.10.mlp.up_proj.lora_A.default.weight True
base_model.model.model.layers.10.mlp.up_proj.lora_B.default.weight True
base_model.model.model.layers.10.mlp.down_proj.base_layer.weight False
base_model.model.model.layers.10.mlp.down_proj.lora_A.default.weight True
base_model.model.model.layers.10.mlp.down_proj.lora_B.default.weight True
base_model.model.model.layers.10.input_layernorm.weight False
base_model.model.model.layers.10.post_attention_layernorm.weight False

<details>
<summary>**LoRA Trainable Parameters**</summary>

What controls trainable params in LoRA

r (rank) → linear scale. Bigger r = more params.

target_modules → which linear layers get LoRA.

Model shapes → each layer’s in/out features (from the arch).

#layers → multiplied across all decoder layers.

Not affecting count: lora_alpha, lora_dropout (they change training dynamics, not how many params).

LoRA param formula (per linear layer)

For a linear layer with shape (out_features, in_features), LoRA adds two small matrices:

A: (r, in) and B: (out, r)

Trainable params = r * (in + out)
(plus tiny scales; we ignore them—they’re negligible)

Apply to your Llama-3.2-3B (from your print)

Hidden = 3072, MLP = 8192, heads = 24, KV heads = 8
So per layer:

q_proj: in=3072, out=3072 → 16(3072+3072) = 98,304*

k_proj: in=3072, out=1024 → 16(3072+1024) = 65,536*

v_proj: in=3072, out=1024 → 65,536

o_proj: in=3072, out=3072 → 98,304

gate_proj: in=3072, out=8192 → 16(3072+8192) = 180,224*

up_proj: same → 180,224

down_proj: in=8192, out=3072 → 180,224

Sum per layer:
98,304 + 65,536 + 65,536 + 98,304 + 180,224*3
= 868,352

- The 28 is the number of transformer decoder layers in your model.

```(layers): ModuleList(
  (0-27): 28 x LlamaDecoderLayer(
    ...
  )
)
```

Each of those layers has the same structure:

attention part (q_proj, k_proj, v_proj, o_proj)

feedforward/MLP part (gate_proj, up_proj, down_proj)

- Layers: 28 → 868,352 × 28 = 24,313,856 ✅ (matches your print)
</details>

In [16]:
# Since your tokenizer already came with a chat template, get_chat_template(...) is not strictly needed. You can still call it if you want consistency checks or to remap EOS tokens.

# 1. Model already has chat template (your case)
# 2. Model has no chat template (e.g., base models like meta-llama/Llama-3-8B)
tokenizer = get_chat_template(
    tokenizer,
    chat_template="qwen3",
    map_eos_token=True  # Maps <|im_end|> to <|eot_id|> if needed,
    #mapping = {"role" : "from", "content" : "value", "user" : "human", "assistant" : "gpt"}, # ShareGPT style
)

In [17]:
print(tokenizer.pad_token)
print(tokenizer.eos_token)

<|vision_pad|>
<|im_end|>

In [18]:
import pandas as pd
import json
from datasets import Dataset

# Step 3: Formatting function for dataset
def formatting_prompts_func(examples):
    convos = []
    lengths = []

    # Iterate through each conversation in the batch
    for convo_json in examples['Conversation']:
        try:
            # Parse the JSON string from the Conversation column
            convo = json.loads(convo_json)
            convos.append(convo)

            # Tokenize the original conversation to get the length
            inputs = tokenizer.apply_chat_template(convo, tokenize=True, add_generation_prompt=False)
            lengths.append(len(inputs))

        except json.JSONDecodeError:
            # Handle invalid JSON by appending an empty conversation or skipping
            convos.append([])  # Or handle as needed (e.g., log error)
            lengths.append(0) # Append 0 length for invalid conversations


    # Apply chat template to each conversation to get the formatted text
    texts = [tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=False) for convo in convos]

    return {"text": texts, "length": lengths}

# Step 4: Convert DataFrame to Hugging Face Dataset
# dataset = Dataset.from_pandas(df[['Conversation']]) # Removed this line as df is not defined

# Step 5: Apply formatting to dataset
dataset = dataset.map(formatting_prompts_func, batched=True)

# Calculate and print the average length
avg_length = sum(dataset['train']['length']) / len(dataset['train']['length'])
print(f"Average token length: {avg_length}")
print("Char count:", len(dataset['train']['text'][0]))

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/40 [00:00<?, ? examples/s]

Map:   0%|          | 0/40 [00:00<?, ? examples/s]

Average token length: 1151.46875
Char count: 5264

In [19]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['id', 'Turn Type', 'Prompt_type', 'tool_name', 'User Queries', 'Roles', 'Missing Parameter', 'tools_in_system_prompt', 'System_Prompt', 'Conversation', 'Miss_para_ground_truth', 'Base_ground_truth_1', 'Base_ground_truth_2', 'text', 'length'],
        num_rows: 320
    })
    validation: Dataset({
        features: ['id', 'Turn Type', 'Prompt_type', 'tool_name', 'User Queries', 'Roles', 'Missing Parameter', 'tools_in_system_prompt', 'System_Prompt', 'Conversation', 'Miss_para_ground_truth', 'Base_ground_truth_1', 'Base_ground_truth_2', 'text', 'length'],
        num_rows: 40
    })
    test: Dataset({
        features: ['id', 'Turn Type', 'Prompt_type', 'tool_name', 'User Queries', 'Roles', 'Missing Parameter', 'tools_in_system_prompt', 'System_Prompt', 'Conversation', 'Miss_para_ground_truth', 'Base_ground_truth_1', 'Base_ground_truth_2', 'text', 'length'],
        num_rows: 40
    })
})

In [20]:
print(dataset['train']['text'][2])

<|im_start|>system
<instructions>
You are an AI assistant with access to a set of tools. Your goal is to accurately and helpfully respond to user queries.

**Workflow:**

1. **Understand Query:** Analyze the user's request and their intent.
2. **Decide Tool Use:**
    * If you can answer directly from your knowledge, do so.
    * If external info/action is needed, use a tool.
3. **Select & Extract Tool Inputs:**
    * Choose the best tool from `Available Tools`.
    * Identify all required parameters from the query.
    * Use default values from the tool specification for any fields not explicitly mentioned by the user.
    * **Always include default values in the tool call, even if the user did not mention them.**
    * Don't make assumptions beyond what's in the query or default values.
4. **Execute Tool (Output Format):**
    * **If you have all required parameters (from user input or defaults), immediately make the tool call.**
    * **Do not ask for missing optional parameters - use defaults.**
    * **Only ask for clarification if absolutely required parameters are missing.**
    * **Once you receive the missing required parameters, immediately make the tool call without further questions.**
    * **If a tool is needed, output the tool call wrapped in `<tool_call>` tags.**
    * **The content within `<tool_call>` MUST be a JSON object containing `name` and `arguments`.**
    * **Format:**
     ```json
     <tool_call>
     {"name": "exact_tool_name", "arguments": {"arg_name1": "value1", "arg_name2": "value2"}}
     </tool_call>
     ```
</instructions>
Here are the available tools:
<tools>
[{"type": "function","function": {"name": "update_inventory_count","description": "Update product inventory quantity","parameters": {"type": "object","properties": {"product_id": {"type": "string","description": "Product identifier"},"quantity_change": {"type": "integer","description": "Quantity delta (positive/negative)"},"reason": {"type": "string","enum": ["sale","purchase","return","damage","adjustment"],"description": "Change reason"},"updated_by": {"type": "string","description": "Employee ID performing update"}},"required": ["product_id","quantity_change","reason","updated_by"]}}},{"type": "function","function": {"name": "create_sales_proposal","description": "Generate a sales proposal for a client.","parameters": {"type": "object","properties": {"client_id": {"type": "string","description": "Client ID."},"proposal_title": {"type": "string","description": "Proposal title."},"products": {"type": "array","description": "Products/services in proposal.","items": {"type": "object","properties": {"product_id": {"type": "string","description": "Product ID."},"quantity": {"type": "integer","description": "Quantity."},"unit_price": {"type": "number","description": "Price per unit."}},"required": ["product_id","quantity","unit_price"]}},"payment_terms": {"type": "object","description": "Payment terms.","properties": {"due_in_days": {"type": "integer","description": "Days until payment due."}}}},"required": ["client_id","proposal_title","products"]}}},{"type": "function","function": {"name": "escalate_support_ticket","description": "Escalate a support ticket to a higher-priority team.","parameters": {"type": "object","properties": {"ticket_id": {"type": "string","description": "Support ticket ID."},"reason": {"type": "string","description": "Reason for escalation (e.g., 'critical', 'unresolved')."},"target_team": {"type": "string","enum": ["senior_support","engineering","billing"],"description": "Team to escalate to."},"notify_customer": {"type": "boolean","default": true,"description": "Notify customer about escalation."}},"required": ["ticket_id","reason","target_team"]}}}]
</tools><|im_end|>
<|im_start|>user
I need to update inventory for product PROD002. We sold 15 units today, so please reduce the count by 15 and mark it as a sale. Updated by EMP456.<|im_end|>
<|im_start|>assistant
<tool_call>[
  {
    "name": "update_inventory_count",
    "arguments": {
      "product_id": "PROD002",
      "quantity_change": -15,
      "reason": "sale",
      "updated_by": "EMP456"
    }
  }
]</tool_call><|im_end|>
<|im_start|>user
Generate a sales proposal for client CUST456 titled 'Enterprise Software Solution'. Include product PROD002 with quantity 5 at $2,000 per unit, 30-day payment terms.<|im_end|>
<|im_start|>assistant
<think>

</think>

<tool_call>[
  {
    "name": "create_sales_proposal",
    "arguments": {
      "client_id": "CUST456",
      "proposal_title": "Enterprise Software Solution",
      "products": [
        {
          "product_id": "PROD002",
          "quantity": 5,
          "unit_price": 2000
        }
      ],
      "payment_terms": {
        "due_in_days": 30
      }
    }
  }
]</tool_call><|im_end|>

In [21]:
print("Char count:", len(dataset['train']['text'][0]))

Char count: 5264

In [22]:
print(dataset['train']['length'][0])

1255

In [23]:
print(dataset['train']['text'][0])
print()
print(type(dataset['train']['text'][0]))

<|im_start|>system
<instructions>
You are an AI assistant with access to a set of tools. Your goal is to accurately and helpfully respond to user queries.

**Workflow:**

1. **Understand Query:** Analyze the user's request and their intent.
2. **Decide Tool Use:**
    * If you can answer directly from your knowledge, do so.
    * If external info/action is needed, use a tool.
3. **Select & Extract Tool Inputs:**
    * Choose the best tool from `Available Tools`.
    * Identify all required parameters from the query.
    * Use default values from the tool specification for any fields not explicitly mentioned by the user.
    * **Always include default values in the tool call, even if the user did not mention them.**
    * Don't make assumptions beyond what's in the query or default values.
4. **Execute Tool (Output Format):**
    * **If you have all required parameters (from user input or defaults), immediately make the tool call.**
    * **Do not ask for missing optional parameters - use defaults.**
    * **Only ask for clarification if absolutely required parameters are missing.**
    * **Once you receive the missing required parameters, immediately make the tool call without further questions.**
    * **If a tool is needed, output the tool call wrapped in `<tool_call>` tags.**
    * **The content within `<tool_call>` MUST be a JSON object containing `name` and `arguments`.**
    * **Format:**
     ```json
     <tool_call>
     {"name": "exact_tool_name", "arguments": {"arg_name1": "value1", "arg_name2": "value2"}}
     </tool_call>
     ```
</instructions>
Here are the available tools:
<tools>
[{"type": "function","function": {"name": "update_inventory_count","description": "Update product inventory quantity","parameters": {"type": "object","properties": {"product_id": {"type": "string","description": "Product identifier"},"quantity_change": {"type": "integer","description": "Quantity delta (positive/negative)"},"reason": {"type": "string","enum": ["sale","purchase","return","damage","adjustment"],"description": "Change reason"},"updated_by": {"type": "string","description": "Employee ID performing update"}},"required": ["product_id","quantity_change","reason","updated_by"]}}},{"type": "function","function": {"name": "create_performance_review","description": "Create a performance review for an employee.","parameters": {"type": "object","properties": {"employee_id": {"type": "string","description": "ID of the employee being reviewed"},"reviewer_id": {"type": "string","description": "ID of the reviewer (manager/supervisor)"},"review_period": {"type": "object","properties": {"start_date": {"type": "string","description": "Review period start date (YYYY-MM-DD)"},"end_date": {"type": "string","description": "Review period end date (YYYY-MM-DD)"}},"required": ["start_date","end_date"]},"overall_rating": {"type": "integer","description": "Performance rating (1-5 scale)","minimum": 1,"maximum": 5},"review_type": {"type": "string","enum": ["annual","mid_year","quarterly","probationary"],"description": "Type of review"}},"required": ["employee_id","reviewer_id","review_period","overall_rating"]}}},{"type": "function","function": {"name": "conduct_compliance_audit","description": "Execute a compliance audit with risk assessment and reporting.","parameters": {"type": "object","properties": {"audit_id": {"type": "string","description": "Unique identifier for the audit"},"regulatory_frameworks": {"type": "array","items": {"type": "string","enum": ["GDPR","HIPAA","SOX","PCI_DSS","ISO_27001","CCPA","SOC2","FISMA"]},"description": "Frameworks to audit against"},"business_units": {"type": "array","items": {"type": "string"},"description": "Business units to include"},"audit_period": {"type": "object","properties": {"start_date": {"type": "string","description": "Audit start date (YYYY-MM-DD)"},"end_date": {"type": "string","description": "Audit end date (YYYY-MM-DD)"}},"required": ["start_date","end_date"]},"lead_auditor": {"type": "string","description": "Employee ID of lead auditor"},"risk_categories": {"type": "array","items": {"type": "string","enum": ["data_privacy","financial_reporting","operational","security","environmental","employment"]},"description": "Risk categories to evaluate"},"materiality_threshold": {"type": "number","description": "Financial materiality threshold"},"automated_testing": {"type": "boolean","default": true,"description": "Enable automated testing"}},"required": ["audit_id","regulatory_frameworks","business_units","audit_period","lead_auditor","risk_categories"]}}}]
</tools><|im_end|>
<|im_start|>user
I need to update inventory. We sold 15 units today, so please reduce the count by 15 and mark it as a sale. Updated by EMP002.<|im_end|>
<|im_start|>assistant
Sure—what’s the product ID for the item you want to update? Once I have that, I’ll reduce the inventory by 15, mark the reason as “sale,” and note it was updated by EMP002.<|im_end|>
<|im_start|>user
The product_id is PROD001.<|im_end|>
<|im_start|>assistant
<think>

</think>

<tool_call>[
  {
    "name": "update_inventory_count",
    "arguments": {
      "product_id": "PROD001",
      "quantity_change": -15,
      "reason": "sale",
      "updated_by": "EMP002"
    }
  }
]</tool_call><|im_end|>


<class 'str'>

In [24]:
# That line just logs you into Weights & Biases (wandb) so your fine-tuning run can send metrics (loss, lr, eval scores, GPU stats, etc.) to your wandb dashboard.
# there are alternates you can use MLflow, TensorBoard
import wandb
wandb.login(key="82e774378493d206425dcbd1b19301693d3f1e74")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: kunjanshah811 (kunjanshah811-paderborn-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [29]:
# trainer = SFTTrainer(
#     model = model,                    # your LoRA-injected model
#     processing_class = tokenizer,     # tokenizer with chat template
#     train_dataset = dataset['train'], # Access the 'train' split
#     eval_dataset = dataset['validation'],   # Access the 'validation' split
#     dataset_text_field = "text",
#     max_seq_length = 2048,
#     dataset_num_proc = 2,             # parallelism for faster dataset prep
#     packing = False,                  # Can make training 5x faster for short sequences.
#     args = TrainingArguments(
#         per_device_train_batch_size = 4,  # Controls the batch size per device
#         per_device_eval_batch_size=4,
#         gradient_accumulation_steps = 4,  # Accumulates gradients to simulate a larger batch
#         warmup_steps = 10,                 # could be 10
#         learning_rate = 2e-4,             # Sets the learning rate for optimization
#         num_train_epochs = 3,
#         fp16 = not torch.cuda.is_bf16_supported(),
#         bf16 = torch.cuda.is_bf16_supported(),
#         optim = "adamw_8bit",
#         weight_decay = 0.01,              # Regularization term for preventing overfitting
#         lr_scheduler_type = "linear",     # Chooses a linear learning rate decay
#         seed = 3407,
#         output_dir = "outputs",
#         report_to = "wandb",              # Enables Weights & Biases (W&B) logging
#         logging_steps = 10,                # Sets frequency of logging to W&B
#         logging_strategy = "steps",       # Logs metrics at each specified step
#         save_strategy = "epoch",              # 👈 save at end of each epoch
#         eval_strategy = "epoch",              # 👈 run eval after each epoch
#         load_best_model_at_end = True,        # Loads the best model at the end
#         save_only_model = False,
#         save_total_limit=2                    # Saves entire model, not only weights
#     )
# )

num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

<details> <summary>📘 <strong>✅ 1. Why processing_class = tokenizer again?</strong></summary>
🔸What you did earlier:

You applied your tokenizer’s chat template manually in:

texts = [tokenizer.apply_chat_template(...)]


This gave you a new "text" field in your dataset — just plain strings like:

<|start_header_id|>user<|end_header_id|>
What's the capital of France?
<|eot_id|>
...


But you did NOT tokenize the text yet. You only formatted it.

🔸What happens in SFTTrainer

When you pass:

processing_class = tokenizer


it tells the trainer:

“Use this tokenizer to tokenize each "text" entry in the dataset into input IDs and attention masks, and apply smart loss masking (like mask user tokens, train only on assistant tokens).”

🔍 Under the hood:

processing_class must implement the method apply_chat_template(...) and internally connect to PreTrainedTokenizer’s __call__ to tokenize.

The SFTTrainer expects text to be raw strings, and tokenizes it itself using the tokenizer + its template.

🧠 So even if you apply the template manually, you still need to give the tokenizer again so SFTTrainer can tokenize it properly with correct EOS tokens, attention mask, and loss mask.

</details>

<details> <summary>📘 <strong>✅ 2. Why again max_seq_length = 1024?</strong></summary>
🔸You set it earlier when loading model
model, tokenizer = FastLanguageModel.from_pretrained(..., max_seq_length=1024)


That only tells the model how long sequences you intend to use (so rope embeddings or position IDs are sized correctly). It’s like saying:

“Hey model, I’ll never feed you more than 1024 tokens.”

But that doesn’t mean the trainer or data loader will obey that unless you tell them too.

🔸Now in SFTTrainer, you set it again:
max_seq_length=1024


This controls:

Tokenization: truncate any input that goes beyond 1024 tokens

Padding: pad shorter examples to 1024

Batching: ensures all sequences are same length → allows tensor batching

🔍 Under the hood:

The trainer will tokenize each "text" with:

tokenizer(text, max_length=1024, padding='max_length', truncation=True)


which happens in the data collator logic before feeding data into the model.
</details>

<details> <summary>📘 <strong>✅ 3. dataset_num_proc = 2 </strong></summary>
This controls how many processes to use for processing the dataset (like .map() calls, tokenization, formatting, etc.).

What it does:

Uses 2 CPU processes in parallel to speed up dataset preprocessing.

Why it matters:

Your dataset has raw conversations → these need to be formatted and tokenized.

If your dataset is large, doing this with num_proc=1 is slow.

With num_proc=2, it runs 2 workers in parallel, so it's ~2× faster.

What other values you can use:

None → defaults to 1 process (slower)

4, 8, 16 → go higher if you have more CPU cores available

🎯 Tip:
Set dataset_num_proc = os.cpu_count() or experiment with 4–8 depending on your machine.

Other values you can set:

dataset_num_proc=4, 8, etc. (depends on your CPU).

Too high? It might crash with memory error.

Safe bet = number of physical CPU cores.

What happens if you don’t set it?

It runs sequentially, which is fine for small data but slow on big datasets.
</details>

<details> <summary>📘 <strong>✅ 4. packing = False </strong></summary>
This means:
"Don’t try to combine multiple short examples into one long token sequence."

Why it matters:

Each of your examples (prompt + response) becomes a token sequence.

Some examples may be very short (e.g., 50 tokens).

If packing=True, it will combine multiple short samples into one long 1024-token chunk.

This wastes fewer tokens, so training is much faster — like 2x to 5x faster.

But:

With packing=True, each training sample might contain multiple conversations → this can confuse the model if you don’t format EOS tokens correctly.

Also can break loss masking (important for SFT).

Why False is safe for now:

You’re doing SFT with loss masking, so each example should stay clean → one prompt → one output → one loss.

packing=False = slower, but more correct for now.
</details>

<details> <summary>📘 <strong>✅ per_device_train_batch_size = 8 </strong></summary>
What it means: This tells the model to process 8 training examples at a time on each GPU (in your case, one Tesla T4).
Real meaning: Think of it like studying 8 questions at once before making a small adjustment to what you’ve learned. A batch size of 8 is a balance between learning speed and GPU memory usage.
Link: Combines with gradient_accumulation_steps = 2 to create an effective batch size of 16 (8 × 2). This means the model learns from 16 examples before updating its weights, but only uses memory for 8 at a time, keeping your GPU happy.
</details>

<details> <summary>📘 <strong>✅ gradient_accumulation_steps = 2 </strong></summary>
What is Gradient Accumulation?
When fine-tuning a neural network (like the Llama model in your notebook), the model learns by adjusting its internal settings (called weights) based on examples it sees. To do this efficiently, it processes multiple examples at once in a "batch." However, large batches require a lot of GPU memory, which can be a problem if your GPU (like the Tesla T4 with 14.741 GB) can’t handle it.
Gradient accumulation is a trick to mimic a larger batch size without needing more GPU memory. Instead of updating the model’s weights after processing one batch, it collects (or "accumulates") the learning updates (called gradients) over multiple smaller batches before applying them.
What Does gradient_accumulation_steps = 2 Mean?

Batch Size: Let’s say your batch size is 8 examples (i.e., batch_size = 8).
Gradient Accumulation Steps = 2: This means the model processes 2 batches (2 × 8 = 16 examples) before updating its weights.
Effective Batch Size: The model behaves as if it processed 16 examples at once (8 × 2 = 16), even though it only used the memory for 8 examples at a time.

Real Meaning in Your Fine-Tuning Setup
In your notebook, you’re fine-tuning a Llama model using a dataset (train-00000-of-00001.parquet) with 1,418 examples for a function-calling task. Here’s what gradient accumulation does:

Saves GPU Memory:

Your Tesla T4 has limited memory (14.741 GB). Processing a large batch (e.g., 16 examples) at once might be too much for the GPU.
With gradient_accumulation_steps = 2, the model processes 8 examples at a time (fitting within memory), collects the learning updates, then processes another 8 examples, and only then updates the weights. This mimics a batch of 16 without crashing the GPU.


Improves Learning:

Larger effective batch sizes (like 16) can make the model’s learning more stable because it sees more examples before deciding how to adjust its weights.
Think of it like studying: reviewing 16 questions before updating your understanding is often better than reviewing just 8, but you still only study 8 at a time to avoid overwhelm.


How It Works in Practice:

For each training step:

Step 1: Process batch 1 (8 examples), calculate gradients, but don’t update weights.
Step 2: Process batch 2 (8 more examples), add gradients to the first batch’s gradients.
Update: Combine the gradients from both steps and update the model’s weights as if it saw 16 examples at once.


This repeats for all 1,418 examples in your dataset, split into batches.



Why Is This Useful for You?

Low GPU Memory: Your setup uses full precision (load_in_4bit=False), which eats up memory. Gradient accumulation lets you achieve a larger effective batch size (16) without needing a bigger GPU.
Flexibility: If you want an even larger effective batch size (e.g., 32), you can increase gradient_accumulation_steps to 4 (8 × 4 = 32). This uses the same memory as a batch of 8 but mimics a batch of 32.
Trade-Off: More accumulation steps mean slower training (because you process more batches before updating), but it’s worth it if memory is tight.

Example in Your Setup

Your Dataset: 1,418 examples, batch_size = 8, gradient_accumulation_steps = 2.
Effective Batch Size: 16 examples.
Training Steps: The dataset is split into 1,418 ÷ 16 ≈ 89 effective batches. Each batch takes 2 GPU steps (2 × 8 examples), so the model processes 2,836 GPU steps total (1,418 × 2).
Impact: The model learns from 16 examples at a time for stable updates, but only uses memory for 8 examples per step, fitting your Tesla T4’s limits.
</details>

<details> <summary>📘 <strong>✅ warmup_steps = 5 </strong></summary>
What it means: For the first 5 training steps, the model starts with a very small learning rate (how much it adjusts weights) and gradually increases it to the full rate (2e-4).
Real meaning: It’s like warming up before exercise—you start slow to avoid big mistakes early on, then speed up once the model gets the hang of it.
Link: Works with learning_rate = 2e-4 and lr_scheduler_type = "linear". The warmup phase ensures the model doesn’t make drastic changes at the start, and the linear scheduler then smoothly reduces the learning rate over time to fine-tune carefully.
</details>

<details> <summary>📘 <strong>✅ learning_rate = 2e-4 </strong></summary>
What it means: This controls how big the model’s weight adjustments are during training. A value of 2e-4 (0.0002) is small, typical for LoRA fine-tuning.
Real meaning: Imagine tweaking a recipe—you add a tiny pinch of salt each time to avoid overdoing it. A small learning rate ensures the model makes careful updates to improve function-calling without forgetting its pre-trained knowledge.
Link: Ties to warmup_steps = 5 (gradual ramp-up to 0.0002) and lr_scheduler_type = "linear" (gradually lowers it later). It also works with optim = "adamw_8bit" to make precise, memory-efficient updates and weight_decay = 0.01 to keep adjustments balanced.
For you:

Small dataset → more epochs (3–8).

Large dataset → fewer epochs (1–3) to avoid overfitting.

You can also think in terms of steps (dataset size × epochs ÷ batch size).
</details>

<details> <summary>📘 <strong>✅ num_train_epochs = 5</strong></summary>

</details>

<details> <summary>📘 <strong>✅ fp16 = not torch.cuda.is_bf16_supported()</strong></summary>

</details>

<details> <summary>📘 <strong>✅ bf16 = torch.cuda.is_bf16_supported()</strong></summary>

</details>

<details> <summary>📘 <strong>✅ optim = "adamw_8bit"</strong></summary>

</details>

<details> <summary>📘 <strong>✅ weight_decay = 0.01</strong></summary>

</details>

<details> <summary>📘 <strong>✅ lr_scheduler_type = "linear"</strong></summary>

</details>

In [25]:
# Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = NVIDIA A100 80GB PCIe. Max memory = 79.252 GB.
13.1 GB of memory reserved.

In [26]:
!pip install optuna optuna-dashboard

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Collecting optuna
  Downloading optuna-4.5.0-py3-none-any.whl.metadata (17 kB)
Collecting optuna-dashboard
  Downloading optuna_dashboard-0.19.0-py3-none-any.whl.metadata (7.1 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.16.5-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/site-packages (from optuna) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/site-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/site-packages (from optuna) (2.0.43)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/site-packages (from optuna) (6.0.2)
Collecting bottle>=0.13.0 (from optuna-dashboard)
  Downloading bottle-0.13.4-py2.py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/site-packages (from optuna-dashboard) (1.7.1)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/site-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/site-packages (from scikit-learn->optuna-dashboard) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/site-packages (from scikit-learn->optuna-dashboard) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/site-packages (from scikit-learn->optuna-dashboard) (3.6.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.5)
Downloading optuna-4.5.0-py3-none-any.whl (400 kB)
Downloading optuna_dashboard-0.19.0-py3-none-any.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 122.9 MB/s eta 0:00:00
Downloading alembic-1.16.5-py3-none-any.whl (247 kB)
Downloading bottle-0.13.4-py2.py3-none-any.whl (103 kB)
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Downloading mako-1.3.10-py3-none-any.whl (78 kB)
Installing collected packages: bottle, Mako, colorlog, alembic, optuna, optuna-dashboard
Successfully installed Mako-1.3.10 alembic-1.16.5 bottle-0.13.4 colorlog-6.9.0 optuna-4.5.0 optuna-dashboard-0.19.0

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [31]:
# from unsloth import unsloth_train
# trainer_stats = unsloth_train(trainer)

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 3 | Total steps = 60
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
 "-____-"     Trainable parameters = 64,225,280 of 14,832,532,480 (0.43% trained)
wandb: Tracking run with wandb version 0.21.4
wandb: Run data is saved locally in /root/wandb/run-20250915_000354-blwqb7nh
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run solar-plant-9
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/huggingface
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/huggingface/runs/blwqb7nh
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/

Unsloth: Will smartly offload gradients to save VRAM!

Unsloth: Not an error, but Qwen3ForCausalLM does not accept `num_items_in_batch`.
Using gradient accumulation will be very slightly less accurate.
Read more on gradient accumulation issues here: https://unsloth.ai/blog/gradient

In [ ]:
import optuna
optuna.logging.set_verbosity(optuna.logging.INFO)  # ✅ Place this here
import torch
import os
from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template
import torch
from trl import SFTTrainer, SFTConfig
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
import os
import wandb
from huggingface_hub import login
from dotenv import load_dotenv
from unsloth import unsloth_train



# Set W&B API key as environment variable
#os.environ["WANDB_API_KEY"] = " "
wandb.login(key=" ", force=True)  # Login to W&B

def save_parameters_info(model, trial_id, output_dir):
    import io
    os.makedirs(output_dir, exist_ok=True)
    output_file = f"{output_dir}/params_{trial_id}.txt"
    
    # Capture print_trainable_parameters output
    buffer = io.StringIO()
    model.print_trainable_parameters()  # Print to console
    # Unsloth doesn't support file arg, so we capture the print output manually
    # Assuming print_trainable_parameters prints to stdout
    import sys
    sys.stdout = buffer
    model.print_trainable_parameters()
    sys.stdout = sys.__stdout__
    
    with open(output_file, "w") as f:
        f.write("Trainable Parameters:\n")
        f.write(buffer.getvalue() + "\n")
        
        only_lora = all("lora_" in n for n, p in model.named_parameters() if p.requires_grad)
        f.write(f"Only LoRA params trainable: {only_lora}\n")
        f.write("Parameters:\n")
        for name, param in model.named_parameters():
            f.write(f"{name}: {param.requires_grad}\n")
    
    print(f"Trial {trial_id} Parameters:")
    print(buffer.getvalue())
    print(f"Only LoRA params trainable: {only_lora}")
    #print("Parameters:")
    # for name, param in model.named_parameters():
    #     print(f"{name}: {param.requires_grad}")

def objective(trial, model, tokenizer, dataset):

    # Initialize W&B run for this trial
    wandb.init(project="new_unsloth_qwen-14B_tuning", name=f"trial_{trial.number}", settings=wandb.Settings(init_timeout=36000))
    
    # Hyperparameter search space
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 5e-4, log=True)
    r = trial.suggest_categorical("r", [8, 16, 32])
    lora_alpha = trial.suggest_categorical("lora_alpha", [8, 32, 64])
    lora_dropout = trial.suggest_float("lora_dropout", 0.0, 0.1)
    batch_size = trial.suggest_categorical("batch_size", [2, 4, 8])
    grad_accum = trial.suggest_categorical("gradient_accumulation_steps", [2, 4, 8])
    warmup_steps = trial.suggest_int("warmup_steps", 0, 50, step=10)
    weight_decay = trial.suggest_float("weight_decay", 0.0, 0.1)
    lr_scheduler_type = trial.suggest_categorical("lr_scheduler_type", ["linear", "cosine"])
    num_epochs = trial.suggest_int("num_train_epochs", 1, 5)

    hyperparams = {
        "learning_rate": learning_rate,
        "r": r,
        "lora_alpha": lora_alpha,
        "lora_dropout": lora_dropout,
        "batch_size": batch_size,
        "gradient_accumulation_steps": grad_accum,
        "warmup_steps": warmup_steps,
        "weight_decay": weight_decay,
        "lr_scheduler_type": lr_scheduler_type,
        "num_train_epochs": num_epochs
    }
    print(f"Trial {trial.number} Hyperparameters: {hyperparams}")

    # ✅ Ensure 'outputs/' directory exists
    os.makedirs("outputs", exist_ok=True)

    with open(f"outputs/trial_{trial.number}_hyperparams.txt", "w") as f:
        f.write(f"Trial {trial.number} Hyperparameters:\n")
        for key, value in hyperparams.items():
            f.write(f"{key}: {value}\n")
    wandb.log(hyperparams)
    
    # Training arguments
    args = TrainingArguments(
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        gradient_accumulation_steps=grad_accum,
        warmup_steps=warmup_steps,
        learning_rate=learning_rate,
        weight_decay=weight_decay,
        num_train_epochs=num_epochs,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        optim="adamw_8bit",
        lr_scheduler_type=lr_scheduler_type,
        seed=3407,
        output_dir=f"outputs/trial_{trial.number}",
        report_to="wandb",
        logging_steps=10,
        save_strategy="epoch",
        eval_strategy="epoch",
        load_best_model_at_end=True,
        save_total_limit=2,
    )

    # Update LoRA model
    model = FastLanguageModel.get_peft_model(
        model,
        r=r,
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        use_gradient_checkpointing="unsloth",
        use_rslora=False,
        bias="none",
        loftq_config=None,
    )

    # Save and print parameter info
    save_parameters_info(model, trial.number, args.output_dir)

    # Initialize trainer
    trainer = SFTTrainer(
        model=model,
        processing_class=tokenizer,
        train_dataset=dataset["train"],
        eval_dataset=dataset["validation"],
        dataset_text_field="text",
        max_seq_length=2048,
        dataset_num_proc=2,
        packing=False,
        args=args,
    )

    trainer_stats = unsloth_train(trainer)
    eval_results = trainer.evaluate()
    wandb.finish()
    return eval_results["eval_loss"]

# Run Optuna study
study = optuna.create_study(direction="minimize", pruner=optuna.pruners.MedianPruner(), storage="sqlite:///optuna_study.db", load_if_exists=True, study_name="new_unsloth_qwen-14B_tuning")
study.optimize(lambda trial: objective(trial, model, tokenizer, dataset), n_trials=10)

# --- Best Trial Summary ---
print("\n🎯 Best Trial Summary")
best_trial = study.best_trial
print(f"Trial #{best_trial.number}")
print(f"→ Best Validation Loss (eval_loss): {best_trial.value}")
print(f"→ Best Hyperparameters:")
for key, val in best_trial.params.items():
    print(f"   {key}: {val}")

# --- All Trials Summary ---
print("\n📊 All Trials Overview")
for trial in study.trials:
    print(f"Trial {trial.number} | Loss: {trial.value} | State: {trial.state.name} | Params: {trial.params}")

# --- Only Completed Trials ---
completed_trials = [t for t in study.trials if t.state.name == "COMPLETE"]
print(f"\n✅ Completed Trials: {len(completed_trials)} / {len(study.trials)}")
for trial in completed_trials:
    print(f"Trial {trial.number} | Loss: {trial.value} | Params: {trial.params}")

# --- Save as CSV ---
csv_path = "outputs/optuna_trials.csv"
os.makedirs("outputs", exist_ok=True)
study.trials_dataframe().to_csv(csv_path, index=False)
print(f"\n📁 Study results saved to: {csv_path}")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
[I 2025-09-18 23:33:13,803] A new study created in RDB with name: new_unsloth_qwen-14B_tuning
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250918_233313-2mvq8lyb
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run trial_0
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/2mvq8lyb
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.07720766666222961.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.

Trial 0 Hyperparameters: {'learning_rate': 3.117735153165457e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.07720766666222961, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 30, 'weight_decay': 0.00893971748639132, 'lr_scheduler_type': 'linear', 'num_train_epochs': 3}

Unsloth 2025.9.6 patched 40 layers with 0 QKV layers, 0 O layers and 0 MLP layers.

trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330
Trial 0 Parameters:
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330

Only LoRA params trainable: True

Unsloth: Tokenizing ["text"] (num_proc=47):   0%|          | 0/320 [00:00<?, ? examples/s]

num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.

Unsloth: Tokenizing ["text"] (num_proc=40):   0%|          | 0/40 [00:00<?, ? examples/s]

Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 3 | Total steps = 60
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 2 x 1) = 16
 "-____-"     Trainable parameters = 64,225,280 of 14,832,532,480 (0.43% trained)

Unsloth: Will smartly offload gradients to save VRAM!

Unsloth: Not an error, but Qwen3ForCausalLM does not accept `num_items_in_batch`.
Using gradient accumulation will be very slightly less accurate.
Read more on gradient accumulation issues here: https://unsloth.ai/blog/gradient

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:                  batch_size ▁
wandb:                   eval/loss █▃▁▁
wandb:                eval/runtime █▁▁▁
wandb:     eval/samples_per_second ▁███
wandb:       eval/steps_per_second ▁███
wandb: gradient_accumulation_steps ▁
wandb:               learning_rate ▁
wandb:                  lora_alpha ▁
wandb:                lora_dropout ▁
wandb:            num_train_epochs ▁
wandb:                          +8 ...
wandb:
wandb: Run summary:
wandb:                  batch_size 8
wandb:                   eval/loss 0.54831
wandb:                eval/runtime 7.6122
wandb:     eval/samples_per_second 5.255
wandb:       eval/steps_per_second 0.657
wandb: gradient_accumulation_steps 2
wandb:               learning_rate 3e-05
wandb:                  lora_alpha 32
wandb:                lora_dropout 0.07721
wandb:           lr_scheduler_type linear
wandb:                         +14 ...
wandb:
wandb: 🚀 View run trial_0 at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/2mvq8lyb
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250918_233313-2mvq8lyb/logs
[I 2025-09-18 23:43:13,420] Trial 0 finished with value: 0.5483085513114929 and parameters: {'learning_rate': 3.117735153165457e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.07720766666222961, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 30, 'weight_decay': 0.00893971748639132, 'lr_scheduler_type': 'linear', 'num_train_epochs': 3}. Best is trial 0 with value: 0.5483085513114929.
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250918_234313-q5r1id40
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run trial_1
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/q5r1id40
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.08925704542192445.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
/usr/local/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 5 | Total steps = 50
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 4 x 1) = 32
 "-____-"     Trainable parameters = 64,225,280 of 14,832,532,480 (0.43% trained)

Trial 1 Hyperparameters: {'learning_rate': 9.822963498696081e-05, 'r': 16, 'lora_alpha': 8, 'lora_dropout': 0.08925704542192445, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 30, 'weight_decay': 0.0513805200642507, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 5}
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330
Trial 1 Parameters:
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330

Only LoRA params trainable: True

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:                  batch_size ▁
wandb:                   eval/loss █▇▄▂▁▁
wandb:                eval/runtime ▃▁▄█▄▁
wandb:     eval/samples_per_second ▆█▅▁▅█
wandb:       eval/steps_per_second ██▅▁██
wandb: gradient_accumulation_steps ▁
wandb:               learning_rate ▁
wandb:                  lora_alpha ▁
wandb:                lora_dropout ▁
wandb:            num_train_epochs ▁
wandb:                          +8 ...
wandb:
wandb: Run summary:
wandb:                  batch_size 8
wandb:                   eval/loss 0.43807
wandb:                eval/runtime 7.6299
wandb:     eval/samples_per_second 5.242
wandb:       eval/steps_per_second 0.655
wandb: gradient_accumulation_steps 4
wandb:               learning_rate 0.0001
wandb:                  lora_alpha 8
wandb:                lora_dropout 0.08926
wandb:           lr_scheduler_type cosine
wandb:                         +14 ...
wandb:
wandb: 🚀 View run trial_1 at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/q5r1id40
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250918_234313-q5r1id40/logs
[I 2025-09-18 23:59:00,807] Trial 1 finished with value: 0.43806886672973633 and parameters: {'learning_rate': 9.822963498696081e-05, 'r': 16, 'lora_alpha': 8, 'lora_dropout': 0.08925704542192445, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 30, 'weight_decay': 0.0513805200642507, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 5}. Best is trial 1 with value: 0.43806886672973633.
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250918_235900-ym2b0mz5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run trial_2
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/ym2b0mz5
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.009191262625736774.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
/usr/local/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 3 | Total steps = 60
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
 "-____-"     Trainable parameters = 64,225,280 of 14,832,532,480 (0.43% trained)

Trial 2 Hyperparameters: {'learning_rate': 0.00036791651202172047, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.009191262625736774, 'batch_size': 4, 'gradient_accumulation_steps': 4, 'warmup_steps': 10, 'weight_decay': 0.048934544102976124, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 3}
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330
Trial 2 Parameters:
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330

Only LoRA params trainable: True

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:                  batch_size ▁
wandb:                   eval/loss █▁▁▁
wandb:                eval/runtime ▂▃█▁
wandb:     eval/samples_per_second ▇▆▁█
wandb:       eval/steps_per_second ▇▇▁█
wandb: gradient_accumulation_steps ▁
wandb:               learning_rate ▁
wandb:                  lora_alpha ▁
wandb:                lora_dropout ▁
wandb:            num_train_epochs ▁
wandb:                          +8 ...
wandb:
wandb: Run summary:
wandb:                  batch_size 4
wandb:                   eval/loss 0.01647
wandb:                eval/runtime 7.976
wandb:     eval/samples_per_second 5.015
wandb:       eval/steps_per_second 1.254
wandb: gradient_accumulation_steps 4
wandb:               learning_rate 0.00037
wandb:                  lora_alpha 32
wandb:                lora_dropout 0.00919
wandb:           lr_scheduler_type cosine
wandb:                         +14 ...
wandb:
wandb: 🚀 View run trial_2 at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/ym2b0mz5
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250918_235900-ym2b0mz5/logs
[I 2025-09-19 00:09:16,160] Trial 2 finished with value: 0.016471603885293007 and parameters: {'learning_rate': 0.00036791651202172047, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.009191262625736774, 'batch_size': 4, 'gradient_accumulation_steps': 4, 'warmup_steps': 10, 'weight_decay': 0.048934544102976124, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 3}. Best is trial 2 with value: 0.016471603885293007.
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250919_000916-9pyk4g6v
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run trial_3
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/9pyk4g6v
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.050734747572930776.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
/usr/local/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 5 | Total steps = 50
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 4 x 1) = 32
 "-____-"     Trainable parameters = 64,225,280 of 14,832,532,480 (0.43% trained)

Trial 3 Hyperparameters: {'learning_rate': 0.0004450930918472793, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.050734747572930776, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 50, 'weight_decay': 0.062164408265492556, 'lr_scheduler_type': 'linear', 'num_train_epochs': 5}
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330
Trial 3 Parameters:
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330

Only LoRA params trainable: True

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:                  batch_size ▁
wandb:                   eval/loss █▃▁▁▁▁
wandb:                eval/runtime ▄▅▆█▆▁
wandb:     eval/samples_per_second ▅▄▃▁▃█
wandb:       eval/steps_per_second ▆▃▁▁▃█
wandb: gradient_accumulation_steps ▁
wandb:               learning_rate ▁
wandb:                  lora_alpha ▁
wandb:                lora_dropout ▁
wandb:            num_train_epochs ▁
wandb:                          +8 ...
wandb:
wandb: Run summary:
wandb:                  batch_size 8
wandb:                   eval/loss 0.01707
wandb:                eval/runtime 7.6174
wandb:     eval/samples_per_second 5.251
wandb:       eval/steps_per_second 0.656
wandb: gradient_accumulation_steps 4
wandb:               learning_rate 0.00045
wandb:                  lora_alpha 32
wandb:                lora_dropout 0.05073
wandb:           lr_scheduler_type linear
wandb:                         +14 ...
wandb:
wandb: 🚀 View run trial_3 at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/9pyk4g6v
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250919_000916-9pyk4g6v/logs
[I 2025-09-19 00:25:05,498] Trial 3 finished with value: 0.01706581749022007 and parameters: {'learning_rate': 0.0004450930918472793, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.050734747572930776, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 50, 'weight_decay': 0.062164408265492556, 'lr_scheduler_type': 'linear', 'num_train_epochs': 5}. Best is trial 2 with value: 0.016471603885293007.
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250919_002505-p5kph3zr
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run trial_4
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/p5kph3zr
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.0810024935545878.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
/usr/local/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 2 | Total steps = 80
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 64,225,280 of 14,832,532,480 (0.43% trained)

Trial 4 Hyperparameters: {'learning_rate': 8.69385070523794e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.0810024935545878, 'batch_size': 2, 'gradient_accumulation_steps': 4, 'warmup_steps': 0, 'weight_decay': 0.08082603127115462, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 2}
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330
Trial 4 Parameters:
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330

Only LoRA params trainable: True

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:                  batch_size ▁
wandb:                   eval/loss █▁▁
wandb:                eval/runtime █▅▁
wandb:     eval/samples_per_second ▁▄█
wandb:       eval/steps_per_second ▁▄█
wandb: gradient_accumulation_steps ▁
wandb:               learning_rate ▁
wandb:                  lora_alpha ▁
wandb:                lora_dropout ▁
wandb:            num_train_epochs ▁
wandb:                          +8 ...
wandb:
wandb: Run summary:
wandb:                  batch_size 2
wandb:                   eval/loss 0.03691
wandb:                eval/runtime 8.5094
wandb:     eval/samples_per_second 4.701
wandb:       eval/steps_per_second 2.35
wandb: gradient_accumulation_steps 4
wandb:               learning_rate 9e-05
wandb:                  lora_alpha 32
wandb:                lora_dropout 0.081
wandb:           lr_scheduler_type cosine
wandb:                         +14 ...
wandb:
wandb: 🚀 View run trial_4 at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/p5kph3zr
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250919_002505-p5kph3zr/logs
[I 2025-09-19 00:32:42,934] Trial 4 finished with value: 0.03690546751022339 and parameters: {'learning_rate': 8.69385070523794e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.0810024935545878, 'batch_size': 2, 'gradient_accumulation_steps': 4, 'warmup_steps': 0, 'weight_decay': 0.08082603127115462, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 2}. Best is trial 2 with value: 0.016471603885293007.
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250919_003242-uqc7jk4h
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run trial_5
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/uqc7jk4h
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.03915816316739819.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
/usr/local/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 5 | Total steps = 50
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 4 x 1) = 32
 "-____-"     Trainable parameters = 128,450,560 of 14,896,757,760 (0.86% trained)

Trial 5 Hyperparameters: {'learning_rate': 0.00019664725614517082, 'r': 32, 'lora_alpha': 8, 'lora_dropout': 0.03915816316739819, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 20, 'weight_decay': 0.002908480428956506, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 5}
trainable params: 128,450,560 || all params: 14,896,757,760 || trainable%: 0.8623
Trial 5 Parameters:
trainable params: 128,450,560 || all params: 14,896,757,760 || trainable%: 0.8623

Only LoRA params trainable: True

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:                  batch_size ▁
wandb:                   eval/loss █▅▂▁▁▁
wandb:                eval/runtime ▅▁▇██▁
wandb:     eval/samples_per_second ▃█▂▁▁█
wandb:       eval/steps_per_second ▄█▃▃▁█
wandb: gradient_accumulation_steps ▁
wandb:               learning_rate ▁
wandb:                  lora_alpha ▁
wandb:                lora_dropout ▁
wandb:            num_train_epochs ▁
wandb:                          +8 ...
wandb:
wandb: Run summary:
wandb:                  batch_size 8
wandb:                   eval/loss 0.11841
wandb:                eval/runtime 7.621
wandb:     eval/samples_per_second 5.249
wandb:       eval/steps_per_second 0.656
wandb: gradient_accumulation_steps 4
wandb:               learning_rate 0.0002
wandb:                  lora_alpha 8
wandb:                lora_dropout 0.03916
wandb:           lr_scheduler_type cosine
wandb:                         +14 ...
wandb:
wandb: 🚀 View run trial_5 at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/uqc7jk4h
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250919_003242-uqc7jk4h/logs
[I 2025-09-19 00:48:30,708] Trial 5 finished with value: 0.11840704828500748 and parameters: {'learning_rate': 0.00019664725614517082, 'r': 32, 'lora_alpha': 8, 'lora_dropout': 0.03915816316739819, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 20, 'weight_decay': 0.002908480428956506, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 5}. Best is trial 2 with value: 0.016471603885293007.
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250919_004830-ucs49qgz
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run trial_6
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/ucs49qgz
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.04589825375836191.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
/usr/local/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 2 | Total steps = 80
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 2 x 1) = 8
 "-____-"     Trainable parameters = 128,450,560 of 14,896,757,760 (0.86% trained)

Trial 6 Hyperparameters: {'learning_rate': 1.4770247722048933e-05, 'r': 32, 'lora_alpha': 64, 'lora_dropout': 0.04589825375836191, 'batch_size': 4, 'gradient_accumulation_steps': 2, 'warmup_steps': 10, 'weight_decay': 0.020981647937719686, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}
trainable params: 128,450,560 || all params: 14,896,757,760 || trainable%: 0.8623
Trial 6 Parameters:
trainable params: 128,450,560 || all params: 14,896,757,760 || trainable%: 0.8623

Only LoRA params trainable: True

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:                  batch_size ▁
wandb:                   eval/loss █▁▁
wandb:                eval/runtime ▆█▁
wandb:     eval/samples_per_second ▃▁█
wandb:       eval/steps_per_second ▃▁█
wandb: gradient_accumulation_steps ▁
wandb:               learning_rate ▁
wandb:                  lora_alpha ▁
wandb:                lora_dropout ▁
wandb:            num_train_epochs ▁
wandb:                          +8 ...
wandb:
wandb: Run summary:
wandb:                  batch_size 4
wandb:                   eval/loss 0.57127
wandb:                eval/runtime 7.9684
wandb:     eval/samples_per_second 5.02
wandb:       eval/steps_per_second 1.255
wandb: gradient_accumulation_steps 2
wandb:               learning_rate 1e-05
wandb:                  lora_alpha 64
wandb:                lora_dropout 0.0459
wandb:           lr_scheduler_type linear
wandb:                         +14 ...
wandb:
wandb: 🚀 View run trial_6 at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/ucs49qgz
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250919_004830-ucs49qgz/logs
[I 2025-09-19 00:55:26,640] Trial 6 finished with value: 0.5712684988975525 and parameters: {'learning_rate': 1.4770247722048933e-05, 'r': 32, 'lora_alpha': 64, 'lora_dropout': 0.04589825375836191, 'batch_size': 4, 'gradient_accumulation_steps': 2, 'warmup_steps': 10, 'weight_decay': 0.020981647937719686, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}. Best is trial 2 with value: 0.016471603885293007.
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250919_005526-2pltgyxd
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run trial_7
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/2pltgyxd
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.003158273027748171.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
/usr/local/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 3 | Total steps = 240
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 2 x 1) = 4
 "-____-"     Trainable parameters = 64,225,280 of 14,832,532,480 (0.43% trained)

Trial 7 Hyperparameters: {'learning_rate': 5.159646372203158e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.003158273027748171, 'batch_size': 2, 'gradient_accumulation_steps': 2, 'warmup_steps': 0, 'weight_decay': 0.02298176832153377, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 3}
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330
Trial 7 Parameters:
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330

Only LoRA params trainable: True

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:                  batch_size ▁
wandb:                   eval/loss █▁▁▁
wandb:                eval/runtime ▇▇█▁
wandb:     eval/samples_per_second ▂▂▁█
wandb:       eval/steps_per_second ▂▃▁█
wandb: gradient_accumulation_steps ▁
wandb:               learning_rate ▁
wandb:                  lora_alpha ▁
wandb:                lora_dropout ▁
wandb:            num_train_epochs ▁
wandb:                          +8 ...
wandb:
wandb: Run summary:
wandb:                  batch_size 2
wandb:                   eval/loss 0.01651
wandb:                eval/runtime 8.5279
wandb:     eval/samples_per_second 4.69
wandb:       eval/steps_per_second 2.345
wandb: gradient_accumulation_steps 2
wandb:               learning_rate 5e-05
wandb:                  lora_alpha 32
wandb:                lora_dropout 0.00316
wandb:           lr_scheduler_type cosine
wandb:                         +14 ...
wandb:
wandb: 🚀 View run trial_7 at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/2pltgyxd
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250919_005526-2pltgyxd/logs
[I 2025-09-19 01:06:49,771] Trial 7 finished with value: 0.016512833535671234 and parameters: {'learning_rate': 5.159646372203158e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.003158273027748171, 'batch_size': 2, 'gradient_accumulation_steps': 2, 'warmup_steps': 0, 'weight_decay': 0.02298176832153377, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 3}. Best is trial 2 with value: 0.016471603885293007.
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250919_010649-bf4k55d7
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run trial_8
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/bf4k55d7
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.04496855724936719.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
/usr/local/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 2 | Total steps = 40
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 2 x 1) = 16
 "-____-"     Trainable parameters = 128,450,560 of 14,896,757,760 (0.86% trained)

Trial 8 Hyperparameters: {'learning_rate': 2.0228149265433245e-05, 'r': 32, 'lora_alpha': 32, 'lora_dropout': 0.04496855724936719, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 0, 'weight_decay': 0.06353129178338017, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}
trainable params: 128,450,560 || all params: 14,896,757,760 || trainable%: 0.8623
Trial 8 Parameters:
trainable params: 128,450,560 || all params: 14,896,757,760 || trainable%: 0.8623

Only LoRA params trainable: True

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:                  batch_size ▁
wandb:                   eval/loss █▁▁
wandb:                eval/runtime █▇▁
wandb:     eval/samples_per_second ▁▂█
wandb:       eval/steps_per_second ▁▂█
wandb: gradient_accumulation_steps ▁
wandb:               learning_rate ▁
wandb:                  lora_alpha ▁
wandb:                lora_dropout ▁
wandb:            num_train_epochs ▁
wandb:                          +8 ...
wandb:
wandb: Run summary:
wandb:                  batch_size 8
wandb:                   eval/loss 1.01926
wandb:                eval/runtime 7.6239
wandb:     eval/samples_per_second 5.247
wandb:       eval/steps_per_second 0.656
wandb: gradient_accumulation_steps 2
wandb:               learning_rate 2e-05
wandb:                  lora_alpha 32
wandb:                lora_dropout 0.04497
wandb:           lr_scheduler_type linear
wandb:                         +14 ...
wandb:
wandb: 🚀 View run trial_8 at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/bf4k55d7
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250919_010649-bf4k55d7/logs
[I 2025-09-19 01:13:21,007] Trial 8 finished with value: 1.01925528049469 and parameters: {'learning_rate': 2.0228149265433245e-05, 'r': 32, 'lora_alpha': 32, 'lora_dropout': 0.04496855724936719, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 0, 'weight_decay': 0.06353129178338017, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}. Best is trial 2 with value: 0.016471603885293007.
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250919_011321-nkqaksnv
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run trial_9
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/nkqaksnv
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.027189432453958797.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
/usr/local/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 2 | Total steps = 40
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 2 x 1) = 16
 "-____-"     Trainable parameters = 128,450,560 of 14,896,757,760 (0.86% trained)

Trial 9 Hyperparameters: {'learning_rate': 9.396176181199262e-05, 'r': 32, 'lora_alpha': 8, 'lora_dropout': 0.027189432453958797, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 50, 'weight_decay': 0.08493602426316622, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}
trainable params: 128,450,560 || all params: 14,896,757,760 || trainable%: 0.8623
Trial 9 Parameters:
trainable params: 128,450,560 || all params: 14,896,757,760 || trainable%: 0.8623

Only LoRA params trainable: True

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:                  batch_size ▁
wandb:                   eval/loss █▁▁
wandb:                eval/runtime ▇█▁
wandb:     eval/samples_per_second ▂▁█
wandb:       eval/steps_per_second ▁▁█
wandb: gradient_accumulation_steps ▁
wandb:               learning_rate ▁
wandb:                  lora_alpha ▁
wandb:                lora_dropout ▁
wandb:            num_train_epochs ▁
wandb:                          +8 ...
wandb:
wandb: Run summary:
wandb:                  batch_size 8
wandb:                   eval/loss 0.77699
wandb:                eval/runtime 7.6432
wandb:     eval/samples_per_second 5.233
wandb:       eval/steps_per_second 0.654
wandb: gradient_accumulation_steps 2
wandb:               learning_rate 9e-05
wandb:                  lora_alpha 8
wandb:                lora_dropout 0.02719
wandb:           lr_scheduler_type linear
wandb:                         +14 ...
wandb:
wandb: 🚀 View run trial_9 at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning/runs/nkqaksnv
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/new_unsloth_qwen-14B_tuning
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250919_011321-nkqaksnv/logs
[I 2025-09-19 01:19:51,480] Trial 9 finished with value: 0.77698814868927 and parameters: {'learning_rate': 9.396176181199262e-05, 'r': 32, 'lora_alpha': 8, 'lora_dropout': 0.027189432453958797, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 50, 'weight_decay': 0.08493602426316622, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}. Best is trial 2 with value: 0.016471603885293007.

🎯 Best Trial Summary
Trial #2
→ Best Validation Loss (eval_loss): 0.016471603885293007
→ Best Hyperparameters:
   learning_rate: 0.00036791651202172047
   r: 16
   lora_alpha: 32
   lora_dropout: 0.009191262625736774
   batch_size: 4
   gradient_accumulation_steps: 4
   warmup_steps: 10
   weight_decay: 0.048934544102976124
   lr_scheduler_type: cosine
   num_train_epochs: 3

📊 All Trials Overview
Trial 0 | Loss: 0.5483085513114929 | State: COMPLETE | Params: {'learning_rate': 3.117735153165457e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.07720766666222961, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 30, 'weight_decay': 0.00893971748639132, 'lr_scheduler_type': 'linear', 'num_train_epochs': 3}
Trial 1 | Loss: 0.43806886672973633 | State: COMPLETE | Params: {'learning_rate': 9.822963498696081e-05, 'r': 16, 'lora_alpha': 8, 'lora_dropout': 0.08925704542192445, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 30, 'weight_decay': 0.0513805200642507, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 5}
Trial 2 | Loss: 0.016471603885293007 | State: COMPLETE | Params: {'learning_rate': 0.00036791651202172047, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.009191262625736774, 'batch_size': 4, 'gradient_accumulation_steps': 4, 'warmup_steps': 10, 'weight_decay': 0.048934544102976124, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 3}
Trial 3 | Loss: 0.01706581749022007 | State: COMPLETE | Params: {'learning_rate': 0.0004450930918472793, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.050734747572930776, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 50, 'weight_decay': 0.062164408265492556, 'lr_scheduler_type': 'linear', 'num_train_epochs': 5}
Trial 4 | Loss: 0.03690546751022339 | State: COMPLETE | Params: {'learning_rate': 8.69385070523794e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.0810024935545878, 'batch_size': 2, 'gradient_accumulation_steps': 4, 'warmup_steps': 0, 'weight_decay': 0.08082603127115462, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 2}
Trial 5 | Loss: 0.11840704828500748 | State: COMPLETE | Params: {'learning_rate': 0.00019664725614517082, 'r': 32, 'lora_alpha': 8, 'lora_dropout': 0.03915816316739819, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 20, 'weight_decay': 0.002908480428956506, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 5}
Trial 6 | Loss: 0.5712684988975525 | State: COMPLETE | Params: {'learning_rate': 1.4770247722048933e-05, 'r': 32, 'lora_alpha': 64, 'lora_dropout': 0.04589825375836191, 'batch_size': 4, 'gradient_accumulation_steps': 2, 'warmup_steps': 10, 'weight_decay': 0.020981647937719686, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}
Trial 7 | Loss: 0.016512833535671234 | State: COMPLETE | Params: {'learning_rate': 5.159646372203158e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.003158273027748171, 'batch_size': 2, 'gradient_accumulation_steps': 2, 'warmup_steps': 0, 'weight_decay': 0.02298176832153377, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 3}
Trial 8 | Loss: 1.01925528049469 | State: COMPLETE | Params: {'learning_rate': 2.0228149265433245e-05, 'r': 32, 'lora_alpha': 32, 'lora_dropout': 0.04496855724936719, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 0, 'weight_decay': 0.06353129178338017, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}
Trial 9 | Loss: 0.77698814868927 | State: COMPLETE | Params: {'learning_rate': 9.396176181199262e-05, 'r': 32, 'lora_alpha': 8, 'lora_dropout': 0.027189432453958797, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 50, 'weight_decay': 0.08493602426316622, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}

✅ Completed Trials: 10 / 10
Trial 0 | Loss: 0.5483085513114929 | Params: {'learning_rate': 3.117735153165457e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.07720766666222961, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 30, 'weight_decay': 0.00893971748639132, 'lr_scheduler_type': 'linear', 'num_train_epochs': 3}
Trial 1 | Loss: 0.43806886672973633 | Params: {'learning_rate': 9.822963498696081e-05, 'r': 16, 'lora_alpha': 8, 'lora_dropout': 0.08925704542192445, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 30, 'weight_decay': 0.0513805200642507, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 5}
Trial 2 | Loss: 0.016471603885293007 | Params: {'learning_rate': 0.00036791651202172047, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.009191262625736774, 'batch_size': 4, 'gradient_accumulation_steps': 4, 'warmup_steps': 10, 'weight_decay': 0.048934544102976124, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 3}
Trial 3 | Loss: 0.01706581749022007 | Params: {'learning_rate': 0.0004450930918472793, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.050734747572930776, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 50, 'weight_decay': 0.062164408265492556, 'lr_scheduler_type': 'linear', 'num_train_epochs': 5}
Trial 4 | Loss: 0.03690546751022339 | Params: {'learning_rate': 8.69385070523794e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.0810024935545878, 'batch_size': 2, 'gradient_accumulation_steps': 4, 'warmup_steps': 0, 'weight_decay': 0.08082603127115462, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 2}
Trial 5 | Loss: 0.11840704828500748 | Params: {'learning_rate': 0.00019664725614517082, 'r': 32, 'lora_alpha': 8, 'lora_dropout': 0.03915816316739819, 'batch_size': 8, 'gradient_accumulation_steps': 4, 'warmup_steps': 20, 'weight_decay': 0.002908480428956506, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 5}
Trial 6 | Loss: 0.5712684988975525 | Params: {'learning_rate': 1.4770247722048933e-05, 'r': 32, 'lora_alpha': 64, 'lora_dropout': 0.04589825375836191, 'batch_size': 4, 'gradient_accumulation_steps': 2, 'warmup_steps': 10, 'weight_decay': 0.020981647937719686, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}
Trial 7 | Loss: 0.016512833535671234 | Params: {'learning_rate': 5.159646372203158e-05, 'r': 16, 'lora_alpha': 32, 'lora_dropout': 0.003158273027748171, 'batch_size': 2, 'gradient_accumulation_steps': 2, 'warmup_steps': 0, 'weight_decay': 0.02298176832153377, 'lr_scheduler_type': 'cosine', 'num_train_epochs': 3}
Trial 8 | Loss: 1.01925528049469 | Params: {'learning_rate': 2.0228149265433245e-05, 'r': 32, 'lora_alpha': 32, 'lora_dropout': 0.04496855724936719, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 0, 'weight_decay': 0.06353129178338017, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}
Trial 9 | Loss: 0.77698814868927 | Params: {'learning_rate': 9.396176181199262e-05, 'r': 32, 'lora_alpha': 8, 'lora_dropout': 0.027189432453958797, 'batch_size': 8, 'gradient_accumulation_steps': 2, 'warmup_steps': 50, 'weight_decay': 0.08493602426316622, 'lr_scheduler_type': 'linear', 'num_train_epochs': 2}

📁 Study results saved to: outputs/optuna_trials.csv
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330
Trial best Parameters:
trainable params: 64,225,280 || all params: 14,832,532,480 || trainable%: 0.4330

Only LoRA params trainable: True
Saved model to https://huggingface.co/kunjanshah/hp_mt_fine_tuned_unsloth_qwen3_14b_lora

<details> <summary>📘 <strong>✅ 1. Where Does 445 Come From?</strong></summary>
445 is the total training steps across all 5 epochs. Each epoch has ~89 steps (1,418 examples ÷ effective batch size 16), so 89 × 5 = 445.

Calculation:

Dataset size: 1,418 examples.
Effective batch size: per_device_train_batch_size × gradient_accumulation_steps = 8 × 2 = 16 examples.
Steps per epoch: Divide the dataset by the effective batch size:
$ 1,418 \div 16 \approx 88.625 $. Since you can’t have a partial step, this is rounded up to 89 steps per epoch.
Total steps across all epochs: With num_train_epochs = 5, the total steps are:
$ 89 \times 5 = 445 $.


What it means: The model processes the entire dataset (1,418 examples) 5 times, and each pass (epoch) takes 89 steps. Each step processes 16 examples (via 2 GPU steps of 8 examples each). The 445 is the total number of steps across all 5 epochs.
In the output: [ 76/445 ... Epoch 0.84/5] means the training is at step 76 out of 445 total steps, and it’s currently at 0.84 epochs (since $ 76 \div 89 \approx 0.84 $).

</details>

<details> <summary>📘 <strong>✅ 2. What is 0.05 in [ 76/445 24:42 < 2:03:13, 0.05 it/s, Epoch 0.84/5]?</strong></summary>
The 0.05 it/s stands for iterations per second, specifically the number of training steps completed per second.

What it means: The model is processing 0.05 steps per second, meaning each step takes about $ 1 \div 0.05 = 20 $ seconds. This is slow, likely due to the Tesla T4’s limited compute power and the model’s size (even with LoRA and fp16 = True).
In the output:

24:42: Time spent so far (24 minutes, 42 seconds) after 76 steps.
< 2:03:13: Estimated time remaining (2 hours, 3 minutes, 13 seconds) to complete the remaining $ 445 - 76 = 369 $ steps.
Why slow?: The Tesla T4 (14.741 GB) is handling a Llama model with max_seq_length = 2048, fp16 = True, and optim = "adamw_8bit". Gradient accumulation (gradient_accumulation_steps = 2) also doubles the time per effective step (two GPU passes per step).


Link to setup: The slow speed is tied to per_device_train_batch_size = 8 and gradient_accumulation_steps = 2, which trade speed for memory efficiency. Using fp16 and adamw_8bit helps fit the model in memory but doesn’t speed up computation much.

</details>

In [28]:
print(trainer_stats)
eval_results = trainer.evaluate()
print(eval_results)

NameError: name 'trainer_stats' is not defined

In [33]:
wandb.finish()

wandb: updating run metadata
wandb:
wandb: Run history:
wandb:               eval/loss █▁▁▁
wandb:            eval/runtime █▁▁▁
wandb: eval/samples_per_second ▁███
wandb:   eval/steps_per_second ▁███
wandb:             train/epoch ▁▂▂▄▅▅▇████
wandb:       train/global_step ▁▂▂▄▅▅▇████
wandb:         train/grad_norm █▄▁▁▁▁
wandb:     train/learning_rate █▇▆▄▃▁
wandb:              train/loss █▄▂▁▁▁
wandb:
wandb: Run summary:
wandb:               eval/loss 0.02927
wandb:            eval/runtime 6.8748
wandb: eval/samples_per_second 5.818
wandb:   eval/steps_per_second 1.455
wandb:              total_flos 8.289549894721536e+16
wandb:             train/epoch 3
wandb:       train/global_step 60
wandb:         train/grad_norm 0.11252
wandb:     train/learning_rate 0.0
wandb:              train/loss 0.0284
wandb:                      +4 ...
wandb:
wandb: 🚀 View run solar-plant-9 at: https://wandb.ai/kunjanshah811-paderborn-university/huggingface/runs/blwqb7nh
wandb: ⭐️ View project at: https://wandb.ai/kunjanshah811-paderborn-university/huggingface
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250915_000354-blwqb7nh/logs

In [29]:
# Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory         /max_memory*100, 3)
lora_percentage = round(used_memory_for_lora/max_memory*100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training.")
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

NameError: name 'trainer_stats' is not defined

In [ ]:
# Retrain with best hyperparameters
best_params = study.best_params
args = TrainingArguments(
    per_device_train_batch_size=best_params["batch_size"],
    per_device_eval_batch_size=best_params["batch_size"],
    gradient_accumulation_steps=best_params["gradient_accumulation_steps"],
    warmup_steps=best_params["warmup_steps"],
    learning_rate=best_params["learning_rate"],
    weight_decay=best_params["weight_decay"],
    num_train_epochs=best_params["num_train_epochs"],
    fp16=not torch.cuda.is_bf16_supported(),
    bf16=torch.cuda.is_bf16_supported(),
    optim="adamw_8bit",
    lr_scheduler_type=best_params["lr_scheduler_type"],
    seed=3407,
    output_dir="outputs/best_model",
    report_to="wandb",
    logging_steps=10,
    logging_strategy="steps",
    save_strategy="epoch",
    eval_strategy="epoch",
    load_best_model_at_end=True,
    save_total_limit=2,
    push_to_hub=True,  # Enable HF Hub upload
    hub_model_id="kunjanshah/hp_mt_fine_tuned_unsloth_qwen3_14b_lora",  # Replace with your HF username
    hub_token=" ",  # Replace with your HF token
)

model = FastLanguageModel.get_peft_model(
    model,
    r=best_params["r"],
    lora_alpha=best_params["lora_alpha"],
    lora_dropout=best_params["lora_dropout"],
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    use_gradient_checkpointing="unsloth",
    use_rslora=False,
    bias="none",
    loftq_config=None,
)

# Save and print best model parameters
save_parameters_info(model, "best", args.output_dir)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    dataset_text_field="text",
    max_seq_length=2048,
    dataset_num_proc=2,
    packing=False,
    args=args,
)

trainer_stats = unsloth_train(trainer)

# Save best model and tokenizer locally and to HF Hub
model.save_pretrained("outputs/hp_mt_fine_tuned_unsloth_qwen3_14b_lora")
tokenizer.save_pretrained("outputs/hp_mt_fine_tuned_unsloth_qwen3_14b_lora")
model.push_to_hub("kunjanshah/hp_mt_fine_tuned_unsloth_qwen3_14b_lora", token="hf_token")
tokenizer.push_to_hub("kunjanshah/hp_mt_fine_tuned_unsloth_qwen3_14b_lora", token="hf_token")

/usr/local/lib/python3.12/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
num_proc must be <= 40. Reducing num_proc to 40 for dataset of size 40.
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 320 | Num Epochs = 3 | Total steps = 60
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
 "-____-"     Trainable parameters = 64,225,280 of 14,832,532,480 (0.43% trained)
wandb: Tracking run with wandb version 0.22.0
wandb: Run data is saved locally in /root/wandb/run-20250919_012543-oro6eljx
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run chocolate-grass-11
wandb: ⭐️ View project at https://wandb.ai/kunjanshah811-paderborn-university/huggingface
wandb: 🚀 View run at https://wandb.ai/kunjanshah811-paderborn-university/huggingface/runs/oro6eljx

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ...p9r_bajps/adapter_model.safetensors:  36%|###5      | 92.2MB /  257MB

No files have been modified since last commit. Skipping to prevent empty commit.

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  /tmp/tmpr_8ucrjv/tokenizer.json       : 100%|##########| 11.4MB / 11.4MB

No files have been modified since last commit. Skipping to prevent empty commit.

In [ ]:
model.push_to_hub("kunjanshah/multi_turn_fine_tuned_unsloth_qwen3_14b_lora", token="hf_token")
tokenizer.push_to_hub("kunjanshah/multi_turn_fine_tuned_unsloth_qwen3_14b_lora", token="hf_token")

README.md:   0%|          | 0.00/591 [00:00<?, ?B/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ..._14b_lora/adapter_model.safetensors:   0%|          |  618kB /  129MB

Saved model to https://huggingface.co/kunjanshah/multi_turn_fine_tuned_unsloth_qwen3_14b_lora

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ...sloth_qwen3_14b_lora/tokenizer.json: 100%|##########| 11.4MB / 11.4MB

In [ ]:
# Merge LoRA adapters and save locally as 16-bit
model.save_pretrained_merged("multi_turn_fine_tuned_merged_unsloth_qwen3_14b_lora", tokenizer, save_method="merged_16bit")

# Push merged 16-bit model to Hugging Face Hub
model.push_to_hub_merged("kunjanshah/multi_turn_fine_tuned_merged_unsloth_qwen3_14b_lora", tokenizer, save_method="merged_16bit", token="hf_token")

config.json:   0%|          | 0.00/754 [00:00<?, ?B/s]

DEBUG: Removed incorrectly saved weight file: model-00001-of-00003.safetensors
DEBUG: Removed incorrectly saved weight file: model-00002-of-00003.safetensors
DEBUG: Removed incorrectly saved weight file: model-00003-of-00003.safetensors
Found HuggingFace hub cache directory: /root/.cache/huggingface/hub

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Checking cache directory for required files...
Cache check failed: model-00001-of-00006.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Merging weights into 16bit:   0%|                                               | 0/6 [00:00<?, ?it/s]

model-00001-of-00006.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Unsloth: Merging weights into 16bit:  17%|██████▌                                | 1/6 [00:36<03:00, 36.18s/it]

model-00002-of-00006.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Unsloth: Merging weights into 16bit:  33%|█████████████                          | 2/6 [01:13<02:28, 37.04s/it]

model-00003-of-00006.safetensors:   0%|          | 0.00/4.93G [00:00<?, ?B/s]

Unsloth: Merging weights into 16bit:  50%|███████████████████▌                   | 3/6 [01:51<01:51, 37.14s/it]

model-00004-of-00006.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Unsloth: Merging weights into 16bit:  67%|██████████████████████████             | 4/6 [02:28<01:14, 37.12s/it]

model-00005-of-00006.safetensors:   0%|          | 0.00/4.93G [00:00<?, ?B/s]

Unsloth: Merging weights into 16bit:  83%|████████████████████████████████▌      | 5/6 [03:06<00:37, 37.46s/it]

model-00006-of-00006.safetensors:   0%|          | 0.00/4.73G [00:00<?, ?B/s]

Unsloth: Merging weights into 16bit: 100%|███████████████████████████████████████| 6/6 [03:40<00:00, 36.72s/it]

DEBUG: Removed incorrectly saved weight file: model-00001-of-00003.safetensors
DEBUG: Removed incorrectly saved weight file: model-00002-of-00003.safetensors
DEBUG: Removed incorrectly saved weight file: model-00003-of-00003.safetensors

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ...sloth_qwen3_14b_lora/tokenizer.json: 100%|##########| 11.4MB / 11.4MB

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Checking cache directory for required files...
Cache check failed: model-00001-of-00006.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Merging weights into 16bit:   0%|                                               | 0/6 [00:00<?, ?it/s]

model-00001-of-00006.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ...ra/model-00001-of-00006.safetensors:   0%|          | 3.84MB / 4.98GB

Unsloth: Merging weights into 16bit:  17%|██████▌                                | 1/6 [01:38<08:11, 98.39s/it]

model-00002-of-00006.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ...ra/model-00002-of-00006.safetensors:   0%|          | 4.21MB / 4.98GB

Unsloth: Merging weights into 16bit:  33%|█████████████                          | 2/6 [03:12<06:23, 95.93s/it]

model-00003-of-00006.safetensors:   0%|          | 0.00/4.93G [00:00<?, ?B/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ...ra/model-00003-of-00006.safetensors:   0%|          | 4.22MB / 4.93GB

Unsloth: Merging weights into 16bit:  50%|███████████████████                   | 3/6 [04:59<05:02, 100.79s/it]

model-00004-of-00006.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ...ra/model-00004-of-00006.safetensors:   0%|          |  601kB / 4.98GB

Unsloth: Merging weights into 16bit:  67%|█████████████████████████▎            | 4/6 [06:39<03:20, 100.44s/it]

model-00005-of-00006.safetensors:   0%|          | 0.00/4.93G [00:00<?, ?B/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ...ra/model-00005-of-00006.safetensors:   0%|          | 9.05kB / 4.93GB

Unsloth: Merging weights into 16bit:  83%|████████████████████████████████▌      | 5/6 [08:08<01:36, 96.63s/it]

model-00006-of-00006.safetensors:   0%|          | 0.00/4.73G [00:00<?, ?B/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ...ra/model-00006-of-00006.safetensors:   1%|1         | 49.7MB / 4.73GB

Unsloth: Merging weights into 16bit: 100%|███████████████████████████████████████| 6/6 [09:41<00:00, 96.99s/it]

## Inference

# **1. Method: pipeline()**

In [ ]:
prompt = """
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 July 2024

<instructions>
You are an AI assistant with access to a set of tools. Your goal is to accurately and helpfully respond to user queries.

**Workflow:**

1. **Understand Query:** Analyze the user's request and their intent.
2. **Decide Tool Use:**
   * If you can answer directly from your knowledge, do so.
   * If external info/action is needed, use a tool.
3. **Select & Argue Tool:** Choose the best tool from `Available Tools` and extract its `input_args` from the query. Don't make assumptions about what values to plug into functions.
4. **Execute Tool (Output Format):**
    * **If a tool is needed, output the tool call wrapped in `<tool_call>` tags.**
    * **The content within `<tool_call>` MUST be a JSON object containing `name` and `arguments`.**
    * **Format:**
     ```json
     <tool_call>
     {"name": "exact_tool_name", "arguments": {"arg_name1": "value1", "arg_name2": "value2"}}
     </tool_call>
     ```
</instructions>
Here are the available tools:
<tools>
[{"type": "function", "function": {"name": "send_offer_letter", "description": "Send a job offer letter to a candidate.", "parameters": {"type": "object", "properties": {"candidate_id": {"type": "string", "description": "Candidate's unique ID."}, "job_title": {"type": "string", "description": "Job title for the offer."}, "salary_base": {"type": "number", "description": "Base salary amount."}, "start_date": {"type": "string", "description": "Start date (YYYY-MM-DD)."}, "expiration_days": {"type": "integer", "description": "Days before offer expires."}}, "required": ["candidate_id", "job_title", "salary_base", "start_date"]}}}, {"type": "function", "function": {"name": "post_job_opening", "description": "Post a job opening to selected job boards.", "parameters": {"type": "object", "properties": {"job_title": {"type": "string", "description": "Job title (e.g., 'Senior Software Engineer')."}, "job_description": {"type": "string", "description": "Summary of job responsibilities."}, "location": {"type": "string", "description": "Job location (e.g., 'Remote', 'New York, NY')."}, "salary_min": {"type": "number", "description": "Minimum salary (default: USD)."}, "salary_max": {"type": "number", "description": "Maximum salary (default: USD)."}, "required_skills": {"type": "array", "items": {"type": "string"}, "description": "Key skills needed (e.g., ['Python', 'AWS'])."}, "job_type": {"type": "string", "enum": ["Full-time", "Part-time", "Contract", "Internship"], "description": "Type of employment."}, "post_to_boards": {"type": "array", "items": {"type": "string"}, "description": "Job boards to post to (e.g., ['LinkedIn', 'Indeed'])."}}, "required": ["job_title", "job_description", "location", "required_skills"]}}}, {"type": "function", "function": {"name": "schedule_interview", "description": "Schedule an interview with a candidate, including calendar invites and reminders.", "parameters": {"type": "object", "properties": {"candidate_id": {"type": "string", "description": "Unique identifier for the candidate."}, "interviewer_ids": {"type": "array", "items": {"type": "string"}, "description": "List of interviewer IDs."}, "interview_type": {"type": "string", "enum": ["Phone", "Video", "On-site"]}, "scheduled_time": {"type": "string", "format": "date-time", "description": "Scheduled interview time (ISO 8601)."}, "duration_minutes": {"type": "integer", "description": "Duration of the interview in minutes."}, "meeting_link": {"type": "string", "description": "URL for video interviews (if applicable)."}, "send_reminder": {"type": "boolean", "default": true, "description": "Send a reminder 24 hours before the interview."}}, "required": ["candidate_id", "interviewer_ids", "scheduled_time"]}}}]
</tools><|eot_id|><|start_header_id|>user<|end_header_id|>


Let's finalize the details for CAND132. They should receive the proposal for the Marketing Manager role with a $75,000 base, starting on 2024-01-15.<|eot_id|>
<tool_call><|start_header_id|>assistant<|end_header_id|>

"""

In [ ]:
from transformers import pipeline
pipe = pipeline("text-generation", model="kunjanshah/unsloth-llama-function-calling")

adapter_config.json:   0%|          | 0.00/950 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/234 [00:00<?, ?B/s]

adapter_model.safetensors:   0%|          | 0.00/97.3M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [ ]:
result=pipe(prompt, max_new_tokens=1024)

In [ ]:
assistant_response = result[0]['generated_text'][-1]['content']
print(assistant_response)

Absolutely! Making your presentations "smell like fresh possibilities" is a powerful metaphor for enhancing your communication. Here’s how you can apply this idea:

### 1. **Start with a Clear Vision**
- Begin your presentation by painting a vivid picture of what success looks like for your organization or product. This sets the tone for optimism and growth.

### 2. **Use Storytelling Techniques**
- Weave narratives into your data and statistics. People remember stories, not just numbers.
- Highlight successes, milestones, and lessons learned.

### 3. **Incorporate Inspirational Images & Videos**
- Add visuals that evoke a sense of possibility—icons, graphics, or short videos of people working together, innovating, or overcoming challenges.

### 4. **Use Positive, Aspirational Language**
- Avoid jargon and technical terms that might make your audience feel confused or trapped. Use plain English that’s exciting and hopeful.
- Focus on what you can achieve, not just what you are currently doing.

### 5. **Emphasize Choice & Flexibility**
- Highlight the freedom and options available to your audience—whether it’s choosing from different products, working remotely, or pursuing new opportunities.

### 6. **End on a High Note**
- Finish your presentation with a forward-looking message, a call to action, or a vision for what’s next.

### 7. **Design with Clarity & Impact**
- Use clean, modern designs that are easy to follow. Break up text with images, and use bold headings to highlight key points.
- Make sure your slides are interactive enough to keep your audience engaged.

### 8. **Practice Your Storytelling**
- Rehearse your presentation to ensure your message is delivered with confidence and enthusiasm.
- Practice your storytelling voice—make it engaging, optimistic, and authentic.

### 9. **Make It Interactive**
- Include polls, quizzes, or Q&A sessions to keep your audience engaged.
- Use interactive visuals or gamification elements to make your presentation feel like an adventure.

### 10. **End with a Sense of Possibility**
- Leave your audience with a feeling of possibility—something they can work towards, something exciting to look forward to.

By applying these strategies, you can transform your presentations into experiences that smell like fresh possibilities—experiences that inspire, motivate, and energize your audience.

# **2. Method: tokenizer.batch_decode() (batch, static output)**

In [38]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="kunjanshah/multi_turn_fine_tuned_unsloth_qwen3_14b_lora",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)

==((====))==  Unsloth 2025.9.4: Fast Qwen3 patching. Transformers: 4.56.1.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu129. CUDA: 8.0. CUDA Toolkit: 12.9. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.32.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

adapter_model.safetensors:   0%|          | 0.00/129M [00:00<?, ?B/s]

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen3ForCausalLM(
      (model): Qwen3Model(
        (embed_tokens): Embedding(151936, 5120, padding_idx=151654)
        (layers): ModuleList(
          (0-5): 6 x Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=17408, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=17408, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
          )
          (6): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear(
                (base_layer): Linear(in_features=17408, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=17408, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
          )
          (7-18): 12 x Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=17408, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=17408, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
          )
          (19): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )

In [39]:
prompt = [
{
"role": "system",
"content": "<instructions>\nYou are an AI assistant with access to a set of tools. Your goal is to accurately and helpfully respond to user queries.\n\n**Workflow:**\n\n1. **Understand Query:** Analyze the user's request and their intent.\n2. **Decide Tool Use:**\n * If you can answer directly from your knowledge, do so.\n * If external info/action is needed, use a tool.\n3. **Select & Extract Tool Inputs:** \n * Choose the best tool from `Available Tools`.\n * Identify all required parameters from the query.\n * Use default values from the tool specification for any fields not explicitly mentioned by the user.\n * **Always include default values in the tool call, even if the user did not mention them.**\n * Don't make assumptions beyond what's in the query or default values.\n4. **Execute Tool (Output Format):**\n * **If you have all required parameters (from user input or defaults), immediately make the tool call.**\n * **Do not ask for missing optional parameters - use defaults.**\n * **Only ask for clarification if absolutely required parameters are missing.**\n * **Once you receive the missing required parameters, immediately make the tool call without further questions.**\n * **If a tool is needed, output the tool call wrapped in `<tool_call>` tags.**\n * **The content within `<tool_call>` MUST be a JSON object containing `name` and `arguments`.**\n * **Format:**\n ```json\n <tool_call>\n {\"name\": \"exact_tool_name\", \"arguments\": {\"arg_name1\": \"value1\", \"arg_name2\": \"value2\"}}\n </tool_call>\n ```\n</instructions>\nHere are the available tools:\n<tools>\n[{\"type\": \"function\",\"function\": {\"name\": \"update_inventory_count\",\"description\": \"Update product inventory quantity\",\"parameters\": {\"type\": \"object\",\"properties\": {\"product_id\": {\"type\": \"string\",\"description\": \"Product identifier\"},\"quantity_change\": {\"type\": \"integer\",\"description\": \"Quantity delta (positive/negative)\"},\"reason\": {\"type\": \"string\",\"enum\": [\"sale\",\"purchase\",\"return\",\"damage\",\"adjustment\"],\"description\": \"Change reason\"},\"updated_by\": {\"type\": \"string\",\"description\": \"Employee ID performing update\"}},\"required\": [\"product_id\",\"quantity_change\",\"reason\",\"updated_by\"]}}},{\"type\": \"function\",\"function\": {\"name\": \"create_performance_review\",\"description\": \"Create a performance review for an employee.\",\"parameters\": {\"type\": \"object\",\"properties\": {\"employee_id\": {\"type\": \"string\",\"description\": \"ID of the employee being reviewed\"},\"reviewer_id\": {\"type\": \"string\",\"description\": \"ID of the reviewer (manager/supervisor)\"},\"review_period\": {\"type\": \"object\",\"properties\": {\"start_date\": {\"type\": \"string\",\"description\": \"Review period start date (YYYY-MM-DD)\"},\"end_date\": {\"type\": \"string\",\"description\": \"Review period end date (YYYY-MM-DD)\"}},\"required\": [\"start_date\",\"end_date\"]},\"overall_rating\": {\"type\": \"integer\",\"description\": \"Performance rating (1-5 scale)\",\"minimum\": 1,\"maximum\": 5},\"review_type\": {\"type\": \"string\",\"enum\": [\"annual\",\"mid_year\",\"quarterly\",\"probationary\"],\"description\": \"Type of review\"}},\"required\": [\"employee_id\",\"reviewer_id\",\"review_period\",\"overall_rating\"]}}},{\"type\": \"function\",\"function\": {\"name\": \"conduct_compliance_audit\",\"description\": \"Execute a compliance audit with risk assessment and reporting.\",\"parameters\": {\"type\": \"object\",\"properties\": {\"audit_id\": {\"type\": \"string\",\"description\": \"Unique identifier for the audit\"},\"regulatory_frameworks\": {\"type\": \"array\",\"items\": {\"type\": \"string\",\"enum\": [\"GDPR\",\"HIPAA\",\"SOX\",\"PCI_DSS\",\"ISO_27001\",\"CCPA\",\"SOC2\",\"FISMA\"]},\"description\": \"Frameworks to audit against\"},\"business_units\": {\"type\": \"array\",\"items\": {\"type\": \"string\"},\"description\": \"Business units to include\"},\"audit_period\": {\"type\": \"object\",\"properties\": {\"start_date\": {\"type\": \"string\",\"description\": \"Audit start date (YYYY-MM-DD)\"},\"end_date\": {\"type\": \"string\",\"description\": \"Audit end date (YYYY-MM-DD)\"}},\"required\": [\"start_date\",\"end_date\"]},\"lead_auditor\": {\"type\": \"string\",\"description\": \"Employee ID of lead auditor\"},\"risk_categories\": {\"type\": \"array\",\"items\": {\"type\": \"string\",\"enum\": [\"data_privacy\",\"financial_reporting\",\"operational\",\"security\",\"environmental\",\"employment\"]},\"description\": \"Risk categories to evaluate\"},\"materiality_threshold\": {\"type\": \"number\",\"description\": \"Financial materiality threshold\"},\"automated_testing\": {\"type\": \"boolean\",\"default\": true,\"description\": \"Enable automated testing\"}},\"required\": [\"audit_id\",\"regulatory_frameworks\",\"business_units\",\"audit_period\",\"lead_auditor\",\"risk_categories\"]}}}]\n</tools>"
},
{
"role": "user",
"content": "I need to update inventory. We sold 15 units today, so please reduce the count by 15 and mark it as a sale. Updated by EMP002."
}
]

In [6]:
from unsloth import FastLanguageModel
import json

# Initialize model and tokenizer
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="kunjanshah/multi_turn_fine_tuned_unsloth_qwen3_14b_lora",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
    device_map={"": "cuda"}, 
    gpu_memory_utilization=0.8 
)
FastLanguageModel.for_inference(model)

class MultiTurnChat:
    def __init__(self):
        self.conversation_history = []
        
    def start_conversation(self, system_prompt, user_message):
        """Start new conversation"""
        self.conversation_history = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message}
        ]
        return self._generate_response()
    
    def continue_conversation(self, user_message):
        """Add user message and get response"""
        self.conversation_history.append({"role": "user", "content": user_message})
        return self._generate_response()
    
    def _generate_response(self):
        """Generate assistant response"""
        inputs = tokenizer.apply_chat_template(
            self.conversation_history,
            tokenize=True,
            add_generation_prompt=True,
            return_tensors="pt",
        ).to("cuda")
        
        # Add these generation parameters to fix the repetition issue
        outputs = model.generate(
            input_ids=inputs, 
            max_new_tokens=512,  # Reduced from 2048
            use_cache=True,
            do_sample=True,      # Enable sampling
            temperature=0.7,     # Add temperature
            top_p=0.9,          # Add nucleus sampling
            repetition_penalty=1.1,  # Prevent repetition
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id
        )
        
        # Get only the new tokens (assistant response)
        new_tokens = outputs[0][inputs.shape[-1]:]  # Extract only new generated tokens
        response = tokenizer.decode(new_tokens, skip_special_tokens=True)
        
        # Clean up the response
        if "<|im_end|>" in response:
            response = response.split("<|im_end|>")[0]
    
        response = response.strip()
    
        # Add to conversation history
        self.conversation_history.append({"role": "assistant", "content": response})
        
        return response
    
    def extract_tool_call(self, response):
        """Extract tool call if present"""
        tool_call_start = "<tool_call>"
        tool_call_end = "</tool_call>"
        
        if tool_call_start in response and tool_call_end in response:
            tool_start_idx = response.find(tool_call_start) + len(tool_call_start)
            tool_end_idx = response.find(tool_call_end)
            tool_call_text = response[tool_start_idx:tool_end_idx].strip()
            
            try:
                return json.loads(tool_call_text)
            except json.JSONDecodeError:
                return None
        return None
    
    def get_history(self):
        return self.conversation_history.copy()
    
    def save_conversation(self, filename):
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(self.conversation_history, f, indent=2, ensure_ascii=False)

# Initialize chat
chat = MultiTurnChat()

# System prompt
system_prompt = """
<instructions>\nYou are an AI assistant with access to a set of tools. Your goal is to accurately and helpfully respond to user queries.\n\n**Workflow:**\n\n1. **Understand Query:** Analyze the user's request and their intent.\n2. **Decide Tool Use:**\n * If you can answer directly from your knowledge, do so.\n * If external info/action is needed, use a tool.\n3. **Select & Extract Tool Inputs:** \n * Choose the best tool from `Available Tools`.\n * Identify all required parameters from the query.\n * Use default values from the tool specification for any fields not explicitly mentioned by the user.\n * **Always include default values in the tool call, even if the user did not mention them.**\n * Don't make assumptions beyond what's in the query or default values.\n4. **Execute Tool (Output Format):**\n * **If you have all required parameters (from user input or defaults), immediately make the tool call.**\n * **Do not ask for missing optional parameters - use defaults.**\n * **Only ask for clarification if absolutely required parameters are missing.**\n * **Once you receive the missing required parameters, immediately make the tool call without further questions.**\n * **If a tool is needed, output the tool call wrapped in `<tool_call>` tags.**\n * **The content within `<tool_call>` MUST be a JSON object containing `name` and `arguments`.**\n * **Format:**\n ```json\n <tool_call>\n {\"name\": \"exact_tool_name\", \"arguments\": {\"arg_name1\": \"value1\", \"arg_name2\": \"value2\"}}\n </tool_call>\n ```\n</instructions>\nHere are the available tools:\n<tools>\n[{\"type\": \"function\",\"function\": {\"name\": \"track_shipment\",\"description\": \"Track the current status and location of a shipment using tracking number.\",\"parameters\": {\"type\": \"object\",\"properties\": {\"tracking_number\": {\"type\": \"string\",\"description\": \"The unique tracking identifier for the shipment\"},\"carrier\": {\"type\": \"string\",\"description\": \"Shipping carrier name\",\"enum\": [\"FedEx\",\"UPS\",\"DHL\",\"USPS\",\"Amazon Logistics\"]},\"include_history\": {\"type\": \"boolean\",\"description\": \"Whether to include full tracking history\",\"default\": false}},\"required\": [\"tracking_number\",\"carrier\"]}}},{\"type\": \"function\",\"function\": {\"name\": \"create_sales_proposal\",\"description\": \"Generate a sales proposal for a client.\",\"parameters\": {\"type\": \"object\",\"properties\": {\"client_id\": {\"type\": \"string\",\"description\": \"Client ID.\"},\"proposal_title\": {\"type\": \"string\",\"description\": \"Proposal title.\"},\"products\": {\"type\": \"array\",\"description\": \"Products/services in proposal.\",\"items\": {\"type\": \"object\",\"properties\": {\"product_id\": {\"type\": \"string\",\"description\": \"Product ID.\"},\"quantity\": {\"type\": \"integer\",\"description\": \"Quantity.\"},\"unit_price\": {\"type\": \"number\",\"description\": \"Price per unit.\"}},\"required\": [\"product_id\",\"quantity\",\"unit_price\"]}},\"payment_terms\": {\"type\": \"object\",\"description\": \"Payment terms.\",\"properties\": {\"due_in_days\": {\"type\": \"integer\",\"description\": \"Days until payment due.\"}}}},\"required\": [\"client_id\",\"proposal_title\",\"products\"]}}},{\"type\": \"function\",\"function\": {\"name\": \"process_invoice_payment\",\"description\": \"Process an invoice payment.\",\"parameters\": {\"type\": \"object\",\"properties\": {\"invoice_id\": {\"type\": \"string\",\"description\": \"Invoice ID.\"},\"vendor_id\": {\"type\": \"string\",\"description\": \"Vendor ID.\"},\"amount\": {\"type\": \"number\",\"description\": \"Payment amount.\"},\"currency\": {\"type\": \"string\",\"enum\": [\"USD\",\"EUR\",\"GBP\"],\"default\": \"USD\"},\"payment_method\": {\"type\": \"string\",\"enum\": [\"ACH\",\"Wire\",\"Check\"],\"default\": \"ACH\"}},\"required\": [\"invoice_id\",\"vendor_id\",\"amount\"]}}}]\n</tools>"""


# Example usage - Start conversation
print("=== Starting Conversation ===")
initial_message = "Track a shipment with UPS carrier and include the full tracking history."

response1 = chat.start_conversation(system_prompt, initial_message)
print(f"User: {initial_message}")
print(f"Assistant: {response1}")

tool_call1 = chat.extract_tool_call(response1)
if tool_call1:
    print(f"Tool Call: {tool_call1}")

print("\n" + "="*50 + "\n")

# Continue conversation - Example 2
user_message2 = "The tracking_number is 1Z999AA1234567890."
response2 = chat.continue_conversation(user_message2)
print(f"User: {user_message2}")
print(f"Assistant: {response2}")

tool_call2 = chat.extract_tool_call(response2)
if tool_call2:
    print(f"Tool Call: {tool_call2}")

print("\n" + "="*50 + "\n")

# # Continue conversation - Example 3
# user_message3 = "Use product ID LAP001 and update the inventory by reducing 15 units for sale by EMP002"
# response3 = chat.continue_conversation(user_message3)
# print(f"User: {user_message3}")
# print(f"Assistant: {response3}")

# tool_call3 = chat.extract_tool_call(response3)
# if tool_call3:
#     print(f"Tool Call: {tool_call3}")

# Save conversation
chat.save_conversation("conversation.json")
print(f"\nConversation saved! Total turns: {len(chat.get_history())}")

# Print full conversation history
print("\n=== Full Conversation History ===")
for i, turn in enumerate(chat.get_history()):
    print(f"{i+1}. {turn['role'].upper()}: {turn['content'][:100]}...")

==((====))==  Unsloth 2025.9.4: Fast Qwen3 patching. Transformers: 4.56.1.
   \\   /|    NVIDIA A100 80GB PCIe. Num GPUs = 1. Max memory: 79.252 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu129. CUDA: 8.0. CUDA Toolkit: 12.9. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.32.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

=== Starting Conversation ===
User: Track a shipment with UPS carrier and include the full tracking history.
Assistant: I can track that shipment for you. Please provide the UPS tracking number. Once I have it, I’ll retrieve the current status and full tracking history.

==================================================

User: The tracking_number is 1Z999AA1234567890.
Assistant: <think>

</think>

<tool_call>[
  {
    "name": "track_shipment",
    "arguments": {
      "tracking_number": "1Z999AA1234567890",
      "carrier": "UPS",
      "include_history": true
    }
  }
]</tool_call>
Tool Call: [{'name': 'track_shipment', 'arguments': {'tracking_number': '1Z999AA1234567890', 'carrier': 'UPS', 'include_history': True}}]

==================================================


Conversation saved! Total turns: 5

=== Full Conversation History ===
1. SYSTEM:
<instructions>
You are an AI assistant with access to a set of tools. Your goal is to accurately an...
2. USER: Track a shipment with UPS carrier and include the full tracking history....
3. ASSISTANT: I can track that shipment for you. Please provide the UPS tracking number. Once I have it, I’ll retr...
4. USER: The tracking_number is 1Z999AA1234567890....
5. ASSISTANT: <think>

</think>

<tool_call>[
  {
    "name": "track_shipment",
    "arguments": {
      "tracking...

In [40]:
inputs = tokenizer.apply_chat_template(
    prompt,
    tokenize=True,
    add_generation_prompt=True,  # Must add for generation
    return_tensors="pt",
).to("cuda")

outputs = model.generate(input_ids=inputs, max_new_tokens=2048, use_cache=True)
response = tokenizer.batch_decode(outputs, skip_special_tokens=False)[0]

# Extract content after <|im_start|>assistant
start_tag = "<|im_start|>assistant"
end_tag = "<|im_end|>"

if start_tag in response:
    # Find the assistant response section
    assistant_start = response.find(start_tag) + len(start_tag)
    response = response[assistant_start:]

    # Remove everything after <|im_end|>
    if end_tag in response:
        response = response.split(end_tag)[0]

# Clean up the response
response = response.strip()

# Optional: Extract tool call if present
tool_call = None
tool_call_start = "<tool_call>"
tool_call_end = "</tool_call>"

if tool_call_start in response and tool_call_end in response:
    # Extract tool call JSON
    tool_start_idx = response.find(tool_call_start) + len(tool_call_start)
    tool_end_idx = response.find(tool_call_end)
    tool_call_text = response[tool_start_idx:tool_end_idx].strip()

    try:
        import json
        tool_call = json.loads(tool_call_text)
        print(f"Tool Call: {tool_call}")
    except json.JSONDecodeError:
        print(f"Failed to parse tool call: {tool_call_text}")

    # Remove tool call from response text
    response = response.replace(f"{tool_call_start}{tool_call_text}{tool_call_end}", "").strip()

print(f"Assistant Response: {response}")

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

Assistant Response: I can do that. Please provide the product_id to update.

In [ ]:
from datasets import load_dataset
from unsloth import FastLanguageModel
import pandas as pd
from tqdm import tqdm
import time
import json
import re

# Load model
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="kunjanshah/fine_tuned_unsloth_qwen3_14b_lora",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)

# Load test dataset and select first 5 samples
dataset = load_dataset("kunjanshah/new_single_turn_function_calling_split", split="test")
#test_subset = dataset.select(range(min(5, len(dataset))))

results = []

for sample in tqdm(dataset, desc="Generating responses"):
    sample = dict(sample)

    # Parse conversation
    convo = eval(sample["Conversation"]) if isinstance(sample["Conversation"], str) else sample["Conversation"]
    convo = convo[:2]  # Only system and user messages

    # Generate response
    inputs = tokenizer.apply_chat_template(
        convo,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
    ).to("cuda")

    start_time = time.time()
    outputs = model.generate(input_ids=inputs, max_new_tokens=2048, use_cache=True)
    exec_time = time.time() - start_time

    response = tokenizer.batch_decode(outputs, skip_special_tokens=False)[0]

    # Extract assistant response
    start_tag = "<|im_start|>assistant"
    end_tag = "<|im_end|>"

    if start_tag in response:
        assistant_start = response.find(start_tag) + len(start_tag)
        response = response[assistant_start:]

        if end_tag in response:
            response = response.split(end_tag)[0]

    response = response.strip()

    # Extract tool call if present
    tool_call = None
    tool_call_start = "<tool_call>"
    tool_call_end = "</tool_call>"

    if tool_call_start in response and tool_call_end in response:
        tool_start_idx = response.find(tool_call_start) + len(tool_call_start)
        tool_end_idx = response.find(tool_call_end)
        tool_call_text = response[tool_start_idx:tool_end_idx].strip()

        try:
            tool_call = json.loads(tool_call_text)
            # Remove tool call from response text
            response = response.replace(f"{tool_call_start}{tool_call_text}{tool_call_end}", "").strip()
        except json.JSONDecodeError:
            tool_call = None

    # Clean up response text - remove special tags and extra whitespace
    response = re.sub(r'<think>.*?</think>', '', response, flags=re.DOTALL)
    response = re.sub(r'<[^>]+>', '', response)  # Remove any other XML-like tags
    response = re.sub(r'\s+', ' ', response).strip()  # Normalize whitespace

    # Token usage
    input_tokens = inputs.shape[1]
    output_tokens = outputs.shape[1] - input_tokens

    results.append({
        "model_response": response,
        "tool_call": tool_call,
        "actual_call": sample.get("model_response", sample.get("function_call")),
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "execution_time": exec_time,
    })

# Save results
df = pd.DataFrame(results)
df.to_csv("ft_qwen3-14b_.csv", index=False)
print(df.head())

==((====))==  Unsloth 2025.9.2: Fast Qwen3 patching. Transformers: 4.56.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.318 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.32.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Generating responses: 100%|██████████| 143/143 [31:41<00:00, 13.30s/it]

                                      model_response  \
0  { "name": "generate_sales_forecast", "argument...
1  { "name": "create_support_ticket", "arguments"...
2  { "name": "request_vendor_quotation", "argumen...
3  { "name": "create_helpdesk_ticket", "arguments...
4  That’s quite an imaginative way to describe a ...

                                           tool_call actual_call  \
0  {'name': 'generate_sales_forecast', 'arguments...        None
1  {'name': 'create_support_ticket', 'arguments':...        None
2  {'name': 'request_vendor_quotation', 'argument...        None
3  {'name': 'create_helpdesk_ticket', 'arguments'...        None
4                                               None        None

   input_tokens  output_tokens  execution_time
0          1171            103        9.343663
1          1160            119       10.721709
2          1023            135       12.120639
3          1094             99        8.942410
4           864            138       12.390184

# **3. Method: TextStreamer (live, token-by-token streaming)**

In [ ]:
from transformers import TextStreamer

text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(input_ids = prompt, streamer = text_streamer, max_new_tokens = 2048, use_cache = True, pad_token_id = tokenizer.eos_token_id)

In [ ]:
from transformers import TextStreamer

# Ensure 'model' and 'tokenizer' are defined and on the correct device (cuda)
# Ensure 'prompt' variable is defined from previous cells

# Tokenize the prompt for model.generate()
inputs = tokenizer.apply_chat_template(
    prompt,
    tokenize = True,
    add_generation_prompt = True, # Important for the model to know it should generate the assistant's response
    return_tensors = "pt",
).to(model.device) # Ensure inputs are on the same device as the model

# Initialize the streamer for streaming output
text_streamer = TextStreamer(tokenizer, skip_prompt=True)

# Generate the response using model.generate()
# Use a reasonable max_new_tokens value
print("Generating response using model.generate():")
_ = model.generate(
    inputs,
    streamer=text_streamer,
    max_new_tokens=2048, # Set a reasonable limit for new tokens
    use_cache=True # Set pad_token_id to eos_token_id for Llama models
)

# Note: The generated text is printed by the streamer.
# If you need the full generated output as a string, you would capture it differently,
# but using the streamer is good for seeing output as it's generated.

Generating response using model.generate():
<tool_call>
{
  "name": "get_employee_profile",
  "arguments": {
    "employee_id": "EMP123"
  }
}
</tool_call><|eot_id|>

In [ ]:
from datasets import load_dataset
import pandas as pd

# Download the dataset
dataset = load_dataset("kunjanshah/single_turn_function_calling_split", split="test")

# Convert the dataset to a pandas DataFrame
df = dataset.to_pandas()

# Define the local path to save the Excel file
excel_file_path = "single_turn_function_calling_test.xlsx"

# Save the DataFrame to an Excel file
df.to_excel(excel_file_path, index=False)

print(f"Dataset downloaded and saved locally to {excel_file_path}")

README.md:   0%|          | 0.00/799 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/2.01M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/302k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/319k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1134 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/141 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/143 [00:00<?, ? examples/s]

Dataset downloaded and saved locally to single_turn_function_calling_test.xlsx